force-app/main/default/objects/Postal_Code_Assignment__c/Postal_Code_Assignment__c.object-meta.xml
<CustomObject>
    <label>Postal Code Assignment</label>
    <nameField>
        <displayFormat>PCA-{0000000000}</displayFormat>
        <label>Postal Code Assignment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Postal Code Assignments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Postal_Code_Assignment__c/fields/Role__c.field-meta.xml
<CustomField>
    <fullName>Role__c</fullName>
    <label>Role</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Raico_Roles</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Postal_Code_Assignment__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>PostalCodeAssignments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Postal_Code_Range__c/Postal_Code_Range__c.object-meta.xml
<CustomObject>
    <label>Postal Code Range</label>
    <nameField>
        <displayFormat>PCR-{0000000000}</displayFormat>
        <label>Postal Code Range Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Postal Code Ranges</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Postal_Code_Range__c/fields/Post_Code_Prefix__c.field-meta.xml
<CustomField>
    <fullName>Post_Code_Prefix__c</fullName>
    <description>For UK Postal codes</description>
    <label>Post Code Prefix</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Postal_Code_Range__c/fields/Postal_Code_Start__c.field-meta.xml
<CustomField>
    <fullName>Postal_Code_Start__c</fullName>
    <label>Postal Code Start</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Postal_Code_Range__c/fields/PostalCodeAssignment__c.field-meta.xml
<CustomField>
    <fullName>PostalCodeAssignment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Postal Code Assignment</label>
    <referenceTo>Postal_Code_Assignment__c</referenceTo>
    <relationshipLabel>Postal Code Ranges</relationshipLabel>
    <relationshipName>PostalCodeRanges</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Postal_Code_Range__c/fields/PostalCodeEnd__c.field-meta.xml
<CustomField>
    <fullName>PostalCodeEnd__c</fullName>
    <label>Postal Code End</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/globalValueSets/Raico_Roles.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Inside Sales</fullName>
    </customValue>
    <customValue>
        <fullName>Project Sales</fullName>
    </customValue>
    <customValue>
        <fullName>Sales</fullName>
    </customValue>
    <masterLabel>Raico Roles</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/V11_PostalCodeAssignment.cls
public class V11_PostalCodeAssignment {
    
    List<Postal_Code_Range__c> ranges;
    
    
    public V11_PostalCodeAssignment(){
        ranges = [select PostalCodeAssignment__r.Role__c, PostalCodeAssignment__r.User__c, Postal_Code_Start__c,PostalCodeEnd__c,PostalCodeAssignment__r.Country__c, Post_Code_Prefix__c from Postal_Code_Range__c];
    }
    
    public List<Postal_Code_Range__c> getUserAndRole(String postCode, String countryCode)
    {
        Set<String> rolesFound = new Set<String>();
        List<Postal_Code_Range__c> resultRanges = new List<Postal_Code_Range__c>();
        
        for(Postal_Code_Range__c range : ranges){
            if(range.PostalCodeAssignment__r.Country__c == countryCode){
                if(!rolesFound.contains(range.PostalCodeAssignment__r.Role__c)){
                    
                        // Check if the postal code matches for UK (use string prefix matching)
                        if (countryCode == 'UK'|| countryCode == 'GB') {
                            String prefixUK = getCharactersBeforeFirstDigit(postCode);
                            
                            if(String.valueOf(range.Post_Code_Prefix__c) == prefixuk){
                                resultRanges.add(range);
                                rolesFound.add(range.PostalCodeAssignment__r.Role__c);
                            }
                        }
                        // otherwise if normal integer post codes, not like in the UK, use the post code ranges.
                        else{
                        // Convert postCode to Integer since Postal_Code_Start__c and PostalCodeEnd__c are Integer types
                Integer postalCodeInt = Integer.valueOf(postCode); 

                            if(range.Postal_Code_Start__c <= postalCodeInt && range.PostalCodeEnd__c>= postalCodeInt){
                                resultRanges.add(range);
                                rolesFound.add(range.PostalCodeAssignment__r.Role__c);
                            }
                        }
                                        
                }
                
                
            }
        }
        return resultRanges;
    }
    
    public static String getCharactersBeforeFirstDigit(String input) {
        // Remove any leading and trailing whitespace
                 
        Pattern patterns = Pattern.compile('^[A-Z]+');
        Matcher matchers = patterns.matcher(input.trim());
        String sub;
        if(matchers.find()){
        	sub = matchers.group(0);
            
        }   
        return sub;
    }
    
  
    
    public static void setOwnerAndAccountTeam(List<Id> accountIds)
    {
        V11_batchSetAccountTeam batchhandler = new V11_batchSetAccountTeam(accountIds);
        database.executeBatch(batchhandler,200);
    }
    public static void setOwnerContact (List<Id> contacts)
    {
        V11_batchSetContactOwner batchhandler = new V11_batchSetContactOwner(contacts);
        database.executeBatch(batchhandler,200);
    }
    
    
}