force-app/main/default/objects/Account/recordTypes/Account.recordType-meta.xml
<RecordType>
    <fullName>Account</fullName>
    <active>true</active>
    <label>Account</label>
</RecordType>

force-app/main/default/objects/AccountBuildingProjectRelation__c/AccountBuildingProjectRelation__c.object-meta.xml
<CustomObject>
    <label>Account Building Project Relation</label>
    <nameField>
        <displayFormat>ABP-{00}</displayFormat>
        <label>Account Building Project Relation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Building Project Relations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/AccountBuildingProjectRelation__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.Blocked__c</field>
            <operation>notEqual</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Building Projects</relationshipLabel>
    <relationshipName>AccountBuildingProject</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/AccountBuildingProjectRelation__c/fields/BuildingProject__c.field-meta.xml
<CustomField>
    <fullName>BuildingProject__c</fullName>
    <label>Building Project</label>
    <referenceTo>BuildingProject__c</referenceTo>
    <relationshipLabel>Project Participants</relationshipLabel>
    <relationshipName>AccountBuildingProject</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/AccountBuildingProjectRelation__c/fields/Role__c.field-meta.xml
<CustomField>
    <fullName>Role__c</fullName>
    <label>Role</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Architect</fullName>
            </value>
            <value>
                <fullName>General Constructor</fullName>
            </value>
            <value>
                <fullName>Planner of cladding</fullName>
            </value>
            <value>
                <fullName>Building Authority</fullName>
            </value>
            <value>
                <fullName>Builder/ Awarding Office</fullName>
            </value>
            <value>
                <fullName>Investor</fullName>
            </value>
            <value>
                <fullName>Datenpflege ausstehend</fullName>
            </value>
            <value>
                <fullName>Project Manager</fullName>
            </value>
            <value>
                <fullName>Projektsteuerer</fullName>
                <isActive>false</isActive>
                <label>Projektsteuerer</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Bidder__c/Bidder__c.object-meta.xml
<CustomObject>
    <label>Bieter</label>
    <nameField>
        <label>Bidder Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Bieter</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Bidder__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Suggested For Bidder List</relationshipLabel>
    <relationshipName>Bidders</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Bidder__c/fields/Building_Project__c.field-meta.xml
<CustomField>
    <fullName>Building_Project__c</fullName>
    <label>Building Project</label>
    <referenceTo>BuildingProject__c</referenceTo>
    <relationshipName>Bidders</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Bidder__c/fields/ContactPerson__c.field-meta.xml
<CustomField>
    <fullName>ContactPerson__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact Person</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.AccountId</field>
            <operation>equals</operation>
            <valueField>$Source.Account__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Bidders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Bidder__c/fields/Interest__c.field-meta.xml
<CustomField>
    <fullName>Interest__c</fullName>
    <label>Interest</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Interested</fullName>
            </value>
            <value>
                <fullName>Not interested</fullName>
            </value>
            <value>
                <fullName>Interest unknown</fullName>
                <isActive>false</isActive>
                <label>Interest unknown</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Bidder__c/recordTypes/Raico_bidder.recordType-meta.xml
<RecordType>
    <fullName>Raico_bidder</fullName>
    <active>true</active>
    <label>Raico bidder</label>
</RecordType>

force-app/main/default/objects/Building_Project_Team__c/Building_Project_Team__c.object-meta.xml
<CustomObject>
    <label>Building Project Team</label>
    <nameField>
        <displayFormat>BPT-{0000000000}</displayFormat>
        <label>Building Project Team Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Building Project Teams</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Building_Project_Team__c/fields/BuildingProject__c.field-meta.xml
<CustomField>
    <fullName>BuildingProject__c</fullName>
    <label>Building Project</label>
    <referenceTo>BuildingProject__c</referenceTo>
    <relationshipLabel>Building Project Team</relationshipLabel>
    <relationshipName>BuildingProjectTeams</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Building_Project_Team__c/fields/Role__c.field-meta.xml
<CustomField>
    <fullName>Role__c</fullName>
    <label>Role</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Responsible</fullName>
            </value>
            <value>
                <fullName>Project Sales</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Building_Project_Team__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Building_Project_Teams</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/BuildingProject__c/BuildingProject__c.object-meta.xml
<CustomObject>
    <label>Bauvorhaben</label>
    <nameField>
        <label>Building Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Bauvorhaben</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/BuildingProject__c/fields/ComarchBuildingProjectNumber__c.field-meta.xml
<CustomField>
    <fullName>ComarchBuildingProjectNumber__c</fullName>
    <externalId>true</externalId>
    <label>Comarch Building Project Number</label>
    <length>40</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Contact/fields/ContactInfo__c.field-meta.xml
<CustomField>
    <fullName>ContactInfo__c</fullName>
    <formula>Account.Name + BR() + Text(Salutation) + &apos; &apos; + FirstName  + &apos; &apos; + LastName +BR()+ Account.BillingStreet +BR()+ Account.BillingPostalCode +&apos; &apos;+ Account.BillingCity +BR()+ Account.BillingCountry +BR()+&apos;Tel.: &apos;+ Account.Phone +BR()+&apos;Mobil: &apos;+ MobilePhone +BR()+&apos;Mail: &apos;+ Email</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>ContactInfo</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Systems__c/Systems__c.object-meta.xml
<CustomObject>
    <label>System</label>
    <nameField>
        <displayFormat>SYS-{0000000000}</displayFormat>
        <label>Systems Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Systems</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Systems__c/fields/BuildingProjectSystem__c.field-meta.xml
<CustomField>
    <fullName>BuildingProjectSystem__c</fullName>
    <label>Building Project</label>
    <referenceTo>BuildingProject__c</referenceTo>
    <relationshipLabel>Systems</relationshipLabel>
    <relationshipName>Systems</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Systems__c/fields/SystemSize__c.field-meta.xml
<CustomField>
    <fullName>SystemSize__c</fullName>
    <label>System Size</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Systems__c/fields/SystemType__c.field-meta.xml
<CustomField>
    <fullName>SystemType__c</fullName>
    <label>System Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Aluminiumfassade</fullName>
                <label>Aluminum facade</label>
            </value>
            <value>
                <fullName>Holzfassade</fullName>
                <label>Wooden facade</label>
            </value>
            <value>
                <fullName>Stahlfassade</fullName>
                <label>Steel facade</label>
            </value>
            <value>
                <fullName>Aluminiumdach</fullName>
                <label>Aluminum roof</label>
            </value>
            <value>
                <fullName>Holzdach</fullName>
                <label>Wooden roof</label>
            </value>
            <value>
                <fullName>Stahldach</fullName>
                <label>Steel roof</label>
            </value>
            <value>
                <fullName>Aluminium Lochfenster/-Fensterbänder</fullName>
                <label>Aluminum punched window / window frames</label>
            </value>
            <value>
                <fullName>Einsatzfenster</fullName>
                <label>Operational window</label>
            </value>
            <value>
                <fullName>elementierte Lösung THERM+</fullName>
                <label>Modular Solution THERM+</label>
            </value>
            <value>
                <fullName>elementierte Lösung FRAME+</fullName>
                <label>Modular Solution FRAME+</label>
            </value>
            <value>
                <fullName>Hebe Schiebe Türe</fullName>
                <label>Lift-and-slide door</label>
            </value>
            <value>
                <fullName>Holz-Aluminium Fenster</fullName>
                <label>Wood-Aluminum Windows</label>
            </value>
            <value>
                <fullName>Aluminiumtüre</fullName>
                <label>Aluminum door</label>
            </value>
            <value>
                <fullName>Brandschutztüre</fullName>
                <label>Fire protection door</label>
            </value>
            <value>
                <fullName>Dachfenster</fullName>
                <label>Roof window</label>
            </value>
            <value>
                <fullName>Aluminium-Dach</fullName>
                <isActive>false</isActive>
                <label>Aluminium-Dach</label>
            </value>
            <value>
                <fullName>Aluminium-Fassade</fullName>
                <isActive>false</isActive>
                <label>Aluminium-Fassade</label>
            </value>
            <value>
                <fullName>Aluminium-Fenster</fullName>
                <isActive>false</isActive>
                <label>Aluminium-Fenster</label>
            </value>
            <value>
                <fullName>Holz-Dach</fullName>
                <isActive>false</isActive>
                <label>Holz-Dach</label>
            </value>
            <value>
                <fullName>Holz-Fassade</fullName>
                <isActive>false</isActive>
                <label>Holz-Fassade</label>
            </value>
            <value>
                <fullName>Stahl-Dach</fullName>
                <isActive>false</isActive>
                <label>Stahl-Dach</label>
            </value>
            <value>
                <fullName>Stahl-Fassade</fullName>
                <isActive>false</isActive>
                <label>Stahl-Fassade</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Systems__c/fields/SystemUnit__c.field-meta.xml
<CustomField>
    <fullName>SystemUnit__c</fullName>
    <label>System Unit</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>sqm</fullName>
                <default>true</default>
                <label>m²</label>
            </value>
            <value>
                <fullName>quantity</fullName>
            </value>
            <value>
                <fullName>linear meters</fullName>
            </value>
            <value>
                <fullName>kg</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/V11_BuildingProjectControllerExtension.cls
public class V11_BuildingProjectControllerExtension {
    
    private final BuildingProject__c bp;
    public  Attachment  file        { set; get; }
    public  Boolean     hasPicture  { set; get; }
    private String      parentId    { set; get; }
    
    
    public V11_BuildingProjectControllerExtension(ApexPages.StandardController stdController) {
    
        this.bp = (BuildingProject__c)stdController.getRecord();
        
        this.parentId       = String.escapeSingleQuotes(stdController.getId());
        this.hasPicture     = false;

        List<Attachment> attList = new List<Attachment>();
        if (Schema.sObjectType.Attachment.fields.Id.isAccessible() 
            && Schema.sObjectType.Attachment.fields.ParentId.isAccessible()
            && Schema.sObjectType.Attachment.fields.Name.isAccessible()
            && Schema.sObjectType.Attachment.fields.ContentType.isAccessible()
            && Schema.sObjectType.Attachment.fields.BodyLength.isAccessible()) {        
            attList = [ Select ParentId, Name, Id, ContentType, BodyLength 
                                        From Attachment 
                                        where ParentId =: this.parentId and name = 'Contact Picture' limit 1];
        } else {
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.FATAL,'Insufficient access'));
        } /* */
        
        if( attList.size() > 0 ){
            this.file       = attList.get( 0 );
            this.file.Body  = Blob.valueOf('AuxString');
            this.hasPicture = true;
        }

        String fileName = this.bp.ComarchBuildingProjectNumber__c +	' - ' + this.bp.Name +'.pdf';
        String fileNameEncoded = EncodingUtil.urlEncode(fileName, 'UTF-8').replaceAll('\\+','%20');
        Apexpages.currentPage().getHeaders().put('content-disposition', 'inline; filename=' + fileNameEncoded);
    }

   /* @AuraEnabled(cacheable=false)
    public static void syncBPToComarch(Id BuildingProjectId){
        V11_ComarchNumberManager.setNumberBP(BuildingProjectId);
        V11_CreateOutboundCall.insertBuildingProject(BuildingProjectId,'create');
    }*/
    
    
    public List<Contact> getBidders(){
        return [
            SELECT ContactInfo__c,Account.name,salutation,FirstName,LastName,Account.BillingStreet,Account.BillingPostalCode,Account.BillingCity,Account.BillingCountry,Phone,MobilePhone,Email
            FROM Contact
            Where Id in (
            SELECT ContactPerson__c
            FROM Bidder__c
            WHERE Building_Project__c = :bp.Id AND Interest__c = 'Interested' AND RecordType.DeveloperName = 'Raico_bidder')
        ];
    }
    
    public List<Systems__c> getSystems(){
         return[
     
             SELECT SystemType__c, SystemSize__c, SystemUnit__c, BuildingProjectSystem__c 
             FROM Systems__c 
             WHERE BuildingProjectSystem__r.Id =: bp.Id
         
         ];
    }

    public List<Account> getArchs(){
             return[
                 SELECT Name, BillingStreet, BillingPostalCode, BillingCity 
                 FROM Account
                 Where Id in (
                 SELECT Account__c
                 FROM AccountBuildingProjectRelation__c
                 WHERE BuildingProject__c = :bp.Id AND Role__c = 'Architect')
             
             ];
        }
    public List<Account> getGC(){
             return[
                 SELECT Name, BillingStreet, BillingPostalCode, BillingCity 
                 FROM Account
                 Where Id in (
                 SELECT Account__c
                 FROM AccountBuildingProjectRelation__c
                 WHERE BuildingProject__c = :bp.Id AND Role__c = 'General Constructor' )
             
             ];
        }
        
        public List<Account> getPlanner(){
             return[
                 SELECT Name, BillingStreet, BillingPostalCode, BillingCity 
                 FROM Account
                 Where Id in (
                 SELECT Account__c
                 FROM AccountBuildingProjectRelation__c
                 WHERE BuildingProject__c = :bp.Id AND Role__c = 'Planner of cladding' )
             
             ];
        }
        
        public List<Account> getBAuth(){
             return[
                 SELECT Name, BillingStreet, BillingPostalCode, BillingCity 
                 FROM Account
                 Where Id in (
                 SELECT Account__c
                 FROM AccountBuildingProjectRelation__c
                 WHERE BuildingProject__c = :bp.Id AND Role__c = 'Builder/ Awarding Office' )
             
             ];
        }
        
    public List<User> getProjectSalesRep(){
             return[
                 SELECT Name, Phone, Email 
                 FROM User
                 Where Id in (
                 SELECT User__c
                 FROM Building_Project_Team__c
                 WHERE  BuildingProject__c =: bp.Id AND Role__c = 'Project Sales')
             
             ];
        }

}