force-app/main/default/objects/Account/recordTypes/Account.recordType-meta.xml
<RecordType>
    <fullName>Account</fullName>
    <active>true</active>
    <label>Account</label>
</RecordType>

force-app/main/default/objects/Postal_Code_Assignment__c/Postal_Code_Assignment__c.object-meta.xml
<CustomObject>
    <label>Postal Code Assignment</label>
    <nameField>
        <displayFormat>PCA-{0000000000}</displayFormat>
        <label>Postal Code Assignment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Postal Code Assignments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Postal_Code_Assignment__c/fields/Role__c.field-meta.xml
<CustomField>
    <fullName>Role__c</fullName>
    <label>Role</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Raico_Roles</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Postal_Code_Assignment__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>PostalCodeAssignments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Postal_Code_Range__c/Postal_Code_Range__c.object-meta.xml
<CustomObject>
    <label>Postal Code Range</label>
    <nameField>
        <displayFormat>PCR-{0000000000}</displayFormat>
        <label>Postal Code Range Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Postal Code Ranges</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Postal_Code_Range__c/fields/PostalCodeAssignment__c.field-meta.xml
<CustomField>
    <fullName>PostalCodeAssignment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Postal Code Assignment</label>
    <referenceTo>Postal_Code_Assignment__c</referenceTo>
    <relationshipLabel>Postal Code Ranges</relationshipLabel>
    <relationshipName>PostalCodeRanges</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Role_Assignment__c/Role_Assignment__c.object-meta.xml
<CustomObject>
    <label>Role Assignment</label>
    <nameField>
        <displayFormat>RA-{0000000000}</displayFormat>
        <label>Role Assignment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Role Assignments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Role_Assignment__c/fields/Additional_Roles__c.field-meta.xml
<CustomField>
    <fullName>Additional_Roles__c</fullName>
    <label>Additional Roles</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Raico_Roles</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Role_Assignment__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>RaicoCountries</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Role_Assignment__c/fields/Objecttype__c.field-meta.xml
<CustomField>
    <fullName>Objecttype__c</fullName>
    <label>Objecttype</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Account</fullName>
            </value>
            <value>
                <fullName>Building Project</fullName>
                <isActive>false</isActive>
                <label>Building Project</label>
            </value>
            <value>
                <fullName>Opportunity</fullName>
                <isActive>false</isActive>
                <label>Opportunity</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Role_Assignment__c/fields/PrimaryRole__c.field-meta.xml
<CustomField>
    <fullName>PrimaryRole__c</fullName>
    <label>Primary Role</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Raico_Roles</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Role_Assignment__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Account</fullName>
            </value>
            <value>
                <fullName>Fabricator</fullName>
            </value>
            <value>
                <fullName>Architect</fullName>
                <isActive>false</isActive>
                <label>Architect</label>
            </value>
            <value>
                <fullName>Planner</fullName>
                <isActive>false</isActive>
                <label>Planner</label>
            </value>
            <value>
                <fullName>Processor</fullName>
                <isActive>false</isActive>
                <label>Processor</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Raico_Roles.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Inside Sales</fullName>
    </customValue>
    <customValue>
        <fullName>Project Sales</fullName>
    </customValue>
    <customValue>
        <fullName>Sales</fullName>
    </customValue>
    <masterLabel>Raico Roles</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/RaicoCountries.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>AT</fullName>
    </customValue>
    <customValue>
        <fullName>CH</fullName>
    </customValue>
    <customValue>
        <fullName>DE</fullName>
    </customValue>
    <customValue>
        <fullName>FR</fullName>
    </customValue>
    <customValue>
        <fullName>IT</fullName>
    </customValue>
    <customValue>
        <fullName>BG</fullName>
    </customValue>
    <customValue>
        <fullName>BA</fullName>
    </customValue>
    <customValue>
        <fullName>XK</fullName>
    </customValue>
    <customValue>
        <fullName>MD</fullName>
    </customValue>
    <customValue>
        <fullName>HR</fullName>
    </customValue>
    <customValue>
        <fullName>ME</fullName>
    </customValue>
    <customValue>
        <fullName>RO</fullName>
    </customValue>
    <customValue>
        <fullName>RS</fullName>
    </customValue>
    <customValue>
        <fullName>SI</fullName>
    </customValue>
    <customValue>
        <fullName>NL</fullName>
    </customValue>
    <customValue>
        <fullName>UK</fullName>
    </customValue>
    <customValue>
        <fullName>GB</fullName>
    </customValue>
    <masterLabel>Raico Countries</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/V11_batchSetAccountTeam.cls
public class V11_batchSetAccountTeam implements Database.Batchable<sObject>,Database.Stateful{

    List<Id> accountIds;
    List<AccountTeamMember> accTeams;
    List<Role_Assignment__c> roleAssignment;
    V11_PostalCodeAssignment pcaList;

    public V11_batchSetAccountTeam(List<Id> accountIds) 
    {
        this.accountIds = accountIds;
        pcaList = new V11_PostalCodeAssignment();
    }

    public Database.QueryLocator start(Database.BatchableContext bc){

        roleAssignment = [select PrimaryRole__c, Additional_Roles__c, Type__c,Country__c from Role_Assignment__c where Objecttype__c ='Account'];

        return Database.getQueryLocator([SELECT Id, RecordType.Name,BillingPostalCode,BillingCountryCode,OwnerId FROM Account WHERE id in :accountIds AND BillingPostalCode != '']);
    }

    public void execute(Database.BatchableContext bc,List<Account> scope)
    {
        List <Account> updateAccounts = new List<Account>();
        List <AccountTeamMember> accountTeamMembers = new List<AccountTeamMember>();
        List<AccountTeamMember> accTeamsToDelete = new List<AccountTeamMember>();

        for(Account acc:scope)
        {
            

            
           /*integer postalCode;
           String  postalCode;
            
            if(acc.BillingPostalCode.isNumeric()){
                postalCode = Integer.valueOf(acc.BillingPostalCode);
            }else{
                continue;
            } 
*/           
            List<Postal_Code_Range__c> postalCodeAssignment = pcaList.getUserAndRole(acc.BillingPostalCode, acc.BillingCountryCode);
            
            system.debug(postalCodeAssignment.size());
            

            for(Role_Assignment__c ra:roleAssignment)
            {

                if(acc.RecordType.Name != ra.Type__c || acc.BillingCountryCode != ra.Country__c){
                    continue;
                }

                for(Postal_Code_Range__c pca:postalCodeAssignment)
                {   
                    
                    if(pca.PostalCodeAssignment__r.Role__c == ra.PrimaryRole__c)
                    {

                        acc.OwnerId = pca.PostalCodeAssignment__r.User__c;
                        updateAccounts.add(acc);
                        AccountTeamMember atm = new AccountTeamMember();
                        atm.AccountId = acc.Id;
                        atm.UserId = pca.PostalCodeAssignment__r.User__c;
                        atm.TeamMemberRole = pca.PostalCodeAssignment__r.Role__c;
                        atm.AccountAccessLevel = 'Edit';
                        atm.CaseAccessLevel = 'Edit';
                        atm.OpportunityAccessLevel = 'Edit';
                        accountTeamMembers.add(atm);
                        
                        
                    }else if(ra.Additional_Roles__c!= null)
                    {
                        List<String> roles =  ra.Additional_Roles__c.split(';');
                        Set<String> rolesSet = new Set<String>();
                        rolesSet.addAll(roles);

                        if(rolesSet.contains(pca.PostalCodeAssignment__r.Role__c))
                        {
                            AccountTeamMember atm = new AccountTeamMember();
                            atm.AccountId = acc.Id;
                            atm.UserId = pca.PostalCodeAssignment__r.User__c;
                            atm.TeamMemberRole = pca.PostalCodeAssignment__r.Role__c;
                            atm.AccountAccessLevel = 'Edit';
                            atm.CaseAccessLevel = 'Edit';
                            atm.OpportunityAccessLevel = 'Edit';                    
                            accountTeamMembers.add(atm);
                        }
    
                    }
                }
            }    

        }   
        Set<Account> accSet = new Set<Account>();
        accSet.addAll(updateAccounts);
        updateAccounts.clear();
        updateAccounts.addAll(accSet);
        Database.DMLOptions dml = new Database.DMLOptions();
        dml.DuplicateRuleHeader.allowSave = true;
        Database.update(updateAccounts,dml);
        try{
            insert accountTeamMembers;
        }catch(Exception e) {}
        

    }
    public void finish(Database.BatchableContext bc)
    {

    }

}