force-app/main/default/objects/Account/fields/Account_Template__c.field-meta.xml
<CustomField>
    <fullName>Account_Template__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>2000 - Customer, third country except Switzerland English-speaking

2001 - Customer, third country except Switzerland German-speaking

2002 - Customer, third country except Switzerland French-speaking

2010 - Customer, Switzerland German-speaking

2020 - Customer, Switzerland French-speaking

2030 - Customer, Switzerland English-speaking

3000 - Customer, EU except FR English-speaking

3001 - Customer, EU except FR German-speaking

Translated with www.DeepL.com/Translator (free version)</inlineHelpText>
    <label>Account Template</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account_Template__c.Name</field>
            <operation>notEqual</operation>
            <value>Migrated Account</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Account_Template__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Language__c.field-meta.xml
<CustomField>
    <fullName>Language__c</fullName>
    <label>Language</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>de</fullName>
            </value>
            <value>
                <fullName>it</fullName>
            </value>
            <value>
                <fullName>fr</fullName>
            </value>
            <value>
                <fullName>en</fullName>
            </value>
            <value>
                <fullName>es</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Account.recordType-meta.xml
<RecordType>
    <fullName>Account</fullName>
    <active>true</active>
    <label>Account</label>
</RecordType>

force-app/main/default/objects/Account_Template__c/Account_Template__c.object-meta.xml
<CustomObject>
    <label>Account Template</label>
    <nameField>
        <label>Account Template Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Account Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Contact/fields/Language__c.field-meta.xml
<CustomField>
    <fullName>Language__c</fullName>
    <label>Language</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>de</fullName>
                <default>true</default>
                <label>de</label>
            </value>
            <value>
                <fullName>en</fullName>
            </value>
            <value>
                <fullName>es</fullName>
            </value>
            <value>
                <fullName>fr</fullName>
            </value>
            <value>
                <fullName>it</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact__c/Contact__c.object-meta.xml
<CustomObject>
    <description>Messebesucher</description>
    <label>Trade Fair Contact</label>
    <nameField>
        <displayFormat>TFC-{00000}</displayFormat>
        <label>Trade Fair Contact</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Trade Fair Contacts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Contact__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Trade Fair Contacts</relationshipLabel>
    <relationshipName>Trade_Fair_Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Visit_Report_Contact_Relation__c/Visit_Report_Contact_Relation__c.object-meta.xml
<CustomObject>
    <label>Visit Report Contact Relation</label>
    <nameField>
        <label>Visit Report Contact Relation Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Visit Report Contact Relations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Visit_Report_Contact_Relation__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Visit Report Contact Relations</relationshipLabel>
    <relationshipName>Visit_Report_Contact_Relations</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/Visit_Report_Contact_Relation__c/fields/Visit_Report__c.field-meta.xml
<CustomField>
    <fullName>Visit_Report__c</fullName>
    <label>Visit Report</label>
    <referenceTo>VisitReport__c</referenceTo>
    <relationshipLabel>Externe Kontakte</relationshipLabel>
    <relationshipName>Visit_Report_Contact_Relations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/VisitReport__c/VisitReport__c.object-meta.xml
<CustomObject>
    <label>Besuchsbericht</label>
    <nameField>
        <label>Visit Report Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Besuchsberichte</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/VisitReport__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Visit_Reports</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/VisitReport__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Primary Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Visit Report</relationshipLabel>
    <relationshipName>Visit_Reports</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/V11_DeleteVisitReportContactTest.cls
@isTest 
public class V11_DeleteVisitReportContactTest {

    @isTest static void testcontactrelationdelete() {
        
        // create test data
            Account testvraccount = new Account(
            Name = 'Vision Eleven again',
            BillingCountry = 'Germany',
            BillingStreet = 'Pettenkoferstr.',
            BillingCity ='Munich',
            BillingPostalCode = '80336',
            Phone = '+491234565589',
            Account_Template__c = 'a0L7Q000004gmqDUAQ', 
            Language__c = 'en') ;
        
            insert testvraccount;
			
            Contact testvrcontact = new Contact(
			LastName = 'Swain',
			Email = 'Testcontact@v11.co',			
            Language__c = 'en',
            Salutation = 'Mr.',
            Accountid = testvraccount.id);

			insert testvrcontact;
        	
            VisitReport__c testvisitreport = new VisitReport__c(
            Account__c = testvraccount.id,
            Contact__c = testvrcontact.Id,
            Name = 'just visiting'  
            );
            insert testvisitreport;
        
            Visit_Report_Contact_Relation__c testvrcontactrelation = new Visit_Report_Contact_Relation__c(
            Contact__c = testvrcontact.Id,
            Visit_Report__c = testvisitreport.Id    
            );
            
            insert testvrcontactrelation;
        
        // get Visit report contact relation for test setup
        List<Visit_Report_Contact_Relation__c> relationsBeforeDelete = [SELECT Id FROM Visit_Report_Contact_Relation__c WHERE Contact__c = :testvrcontact.Id ];
        
        // get the corresponding contact
        List <Contact> beforedeleterelatedcontact = [SELECT Id FROM Contact WHERE id = :testvrcontact.Id];
        
        //assert that there is at least one contact relation
        System.assertEquals(1, relationsBeforeDelete.size(), 'There should be 1 related Visit_Report_Contact_Relation__c record before deleting the Contact.');
        
        
        delete beforedeleterelatedcontact;
        
        // assert that there are no visit report contact relations after deleting the contact
        List<Visit_Report_Contact_Relation__c> relationsAfterDelete = [SELECT Id FROM Visit_Report_Contact_Relation__c WHERE Contact__c = :testvrcontact.Id];
        System.assertEquals(0, relationsAfterDelete.size(), 'The related Visit_Report_Contact_Relation__c record should be deleted after deleting the Contact.');
        // now that the contact relation has been deleted see that the contact can now be deleted
        
        // assert that the contact has been deleted
        List <Contact> afterdeleterelatedcontact = [SELECT Id FROM Contact WHERE id = :testvrcontact.Id];
        System.assertEquals(0, afterdeleterelatedcontact.size(), 'should be possible to delete the contact');
    }

   @isTest
    static void testDeleteContactWithoutRelation() {
        // Create a test Contact with no relation record
        Contact testContact = new Contact(LastName = 'Test Contact No Relation');
        insert testContact;

        // Delete the contact with no relation to ensure it doesn’t throw an error
        delete testContact;

        // Confirm no exception and no Visit_Report_Contact_Relation__c records
        List<Visit_Report_Contact_Relation__c> relationsAfterDelete = [SELECT Id FROM Visit_Report_Contact_Relation__c WHERE Contact__c = :testContact.Id];
        System.assertEquals(0, relationsAfterDelete.size(), 'No related Visit_Report_Contact_Relation__c records should exist.');
    }
     
  }