force-app/main/default/objects/Account/fields/Account_Template__c.field-meta.xml
<CustomField>
    <fullName>Account_Template__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>2000 - Customer, third country except Switzerland English-speaking

2001 - Customer, third country except Switzerland German-speaking

2002 - Customer, third country except Switzerland French-speaking

2010 - Customer, Switzerland German-speaking

2020 - Customer, Switzerland French-speaking

2030 - Customer, Switzerland English-speaking

3000 - Customer, EU except FR English-speaking

3001 - Customer, EU except FR German-speaking

Translated with www.DeepL.com/Translator (free version)</inlineHelpText>
    <label>Account Template</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account_Template__c.Name</field>
            <operation>notEqual</operation>
            <value>Migrated Account</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Account_Template__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/ComarchAccountNumber__c.field-meta.xml
<CustomField>
    <fullName>ComarchAccountNumber__c</fullName>
    <externalId>true</externalId>
    <label>Comarch Account Number</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Account.recordType-meta.xml
<RecordType>
    <fullName>Account</fullName>
    <active>true</active>
    <label>Account</label>
</RecordType>

force-app/main/default/objects/Account_Template__c/Account_Template__c.object-meta.xml
<CustomObject>
    <label>Account Template</label>
    <nameField>
        <label>Account Template Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Account Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/BuildingProject__c/BuildingProject__c.object-meta.xml
<CustomObject>
    <label>Bauvorhaben</label>
    <nameField>
        <label>Building Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Bauvorhaben</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/BuildingProject__c/fields/ComarchBuildingProjectNumber__c.field-meta.xml
<CustomField>
    <fullName>ComarchBuildingProjectNumber__c</fullName>
    <externalId>true</externalId>
    <label>Comarch Building Project Number</label>
    <length>40</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/BuildingProject__c/fields/Stage__c.field-meta.xml
<CustomField>
    <fullName>Stage__c</fullName>
    <label>Stage</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Research</fullName>
                <default>true</default>
                <label>Research</label>
            </value>
            <value>
                <fullName>Consulting/ Planning</fullName>
            </value>
            <value>
                <fullName>Tender &amp; Quote</fullName>
            </value>
            <value>
                <fullName>Award Fabricator</fullName>
            </value>
            <value>
                <fullName>Award System house</fullName>
            </value>
            <value>
                <fullName>Execution</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
                <label>Completed</label>
            </value>
            <value>
                <fullName>Award</fullName>
                <isActive>false</isActive>
                <label>Award</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/V11_enaioTest.cls
@isTest
public class V11_enaioTest {
    @TestSetup
    static void makeData(){

        Database.DMLOptions dml = new Database.DMLOptions();
        dml.DuplicateRuleHeader.allowSave = true;
        dml.DuplicateRuleHeader.runAsCurrentUser = true;

        Account acc = new Account();
        Account_Template__c temp = new Account_Template__c();
        temp.Key__c ='1000';
        insert temp;

        Account acc1 = new Account();
        acc1.Name = 'Test Number';
        acc1.Account_Template__c = temp.Id;
        acc1.BillingStreet = 'Muster straße';
        acc1.BillingCity = 'Test';
        acc1.BillingPostalCode = '12335';
        acc1.BillingCountryCode = 'DE';
        acc1.ComarchAccountNumber__c = '123';

        Database.insert(acc1,dml);

        BuildingProject__c bp = new BuildingProject__c();
        bp.Name = 'test';
        bp.Amount__c = 123;
        bp.Stage__c = 'Research';
        bp.ComarchBuildingProjectNumber__c='Test';
        bp.ProjectAddress__Street__s='Pettenkoferstraße 13';
        bp.ProjectAddress__City__s='Berlin';
        bp.ProjectAddress__PostalCode__s='10247';
        bp.ProjectAddress__CountryCode__s='DE';
        insert bp;

    }
    static testmethod void sendAccount(){

        Account acc = [SELECT Id,ComarchAccountNumber__c,Name,BillingStreet,BillingCountry,BillingPostalCode,BillingCity FROM Account WHERE ComarchAccountNumber__c = '123'];
        
        Test.startTest();
        Test.setMock(HttpCalloutMock.class, new V11_WebServiceMock('enaio'));

        V11_sendObjectToEnaio queue = new V11_sendObjectToEnaio(acc);
        System.enqueueJob(queue);

        Test.stopTest();

    }

    static testmethod void sendBP(){

        BuildingProject__c bp = [SELECT Id,ComarchBuildingProjectNumber__c,OwnerId,Name, ProjectAddress__City__s FROM BuildingProject__c WHERE ComarchBuildingProjectNumber__c = 'Test'];
        
        Test.startTest();
        Test.setMock(HttpCalloutMock.class, new V11_WebServiceMock('enaio'));

        V11_sendObjectToEnaio queue = new V11_sendObjectToEnaio(bp);
        System.enqueueJob(queue);

        Test.stopTest();

    }
}