force-app/main/default/objects/Account/fields/Account_Template__c.field-meta.xml
<CustomField>
    <fullName>Account_Template__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>2000 - Customer, third country except Switzerland English-speaking

2001 - Customer, third country except Switzerland German-speaking

2002 - Customer, third country except Switzerland French-speaking

2010 - Customer, Switzerland German-speaking

2020 - Customer, Switzerland French-speaking

2030 - Customer, Switzerland English-speaking

3000 - Customer, EU except FR English-speaking

3001 - Customer, EU except FR German-speaking

Translated with www.DeepL.com/Translator (free version)</inlineHelpText>
    <label>Account Template</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account_Template__c.Name</field>
            <operation>notEqual</operation>
            <value>Migrated Account</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Account_Template__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/ComarchAccountNumber__c.field-meta.xml
<CustomField>
    <fullName>ComarchAccountNumber__c</fullName>
    <externalId>true</externalId>
    <label>Comarch Account Number</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/fields/Language__c.field-meta.xml
<CustomField>
    <fullName>Language__c</fullName>
    <label>Language</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>de</fullName>
            </value>
            <value>
                <fullName>it</fullName>
            </value>
            <value>
                <fullName>fr</fullName>
            </value>
            <value>
                <fullName>en</fullName>
            </value>
            <value>
                <fullName>es</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Account.recordType-meta.xml
<RecordType>
    <fullName>Account</fullName>
    <active>true</active>
    <label>Account</label>
</RecordType>

force-app/main/default/objects/Account_Template__c/Account_Template__c.object-meta.xml
<CustomObject>
    <label>Account Template</label>
    <nameField>
        <label>Account Template Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Account Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Contact/fields/ExternalComarchContactId__c.field-meta.xml
<CustomField>
    <fullName>ExternalComarchContactId__c</fullName>
    <externalId>true</externalId>
    <label>Comarch Contact Number</label>
    <length>20</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Contact/fields/Language__c.field-meta.xml
<CustomField>
    <fullName>Language__c</fullName>
    <label>Language</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>de</fullName>
                <default>true</default>
                <label>de</label>
            </value>
            <value>
                <fullName>en</fullName>
            </value>
            <value>
                <fullName>es</fullName>
            </value>
            <value>
                <fullName>fr</fullName>
            </value>
            <value>
                <fullName>it</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Title__c.field-meta.xml
<CustomField>
    <fullName>Title__c</fullName>
    <label>Title</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>ArchitektIn</fullName>
            </value>
            <value>
                <fullName>BSc.</fullName>
            </value>
            <value>
                <fullName>DI Mag.</fullName>
            </value>
            <value>
                <fullName>Dipl.Ing.</fullName>
                <label>Dipl. Ing.</label>
            </value>
            <value>
                <fullName>Dipl. Ing. (FH)</fullName>
            </value>
            <value>
                <fullName>Dipl.-Ing. Arch (FH)</fullName>
            </value>
            <value>
                <fullName>Dipl.-Ing. ArchitektIn</fullName>
            </value>
            <value>
                <fullName>Dipl. Wirt.-Ing (FH)</fullName>
            </value>
            <value>
                <fullName>Dr.</fullName>
            </value>
            <value>
                <fullName>Dr. Dipl. Ing.</fullName>
            </value>
            <value>
                <fullName>Dr. Ing.</fullName>
            </value>
            <value>
                <fullName>Ing.</fullName>
            </value>
            <value>
                <fullName>Ing. Mag.</fullName>
            </value>
            <value>
                <fullName>M.A. Architektin</fullName>
            </value>
            <value>
                <fullName>M. Arch.</fullName>
            </value>
            <value>
                <fullName>Mag.</fullName>
            </value>
            <value>
                <fullName>Mag. Arch.</fullName>
            </value>
            <value>
                <fullName>Mag. MBA</fullName>
            </value>
            <value>
                <fullName>MBA</fullName>
            </value>
            <value>
                <fullName>Prof.</fullName>
            </value>
            <value>
                <fullName>Prof. Dipl. Ing.</fullName>
            </value>
            <value>
                <fullName>Prof. Dr.</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Postal_Code_Assignment__c/Postal_Code_Assignment__c.object-meta.xml
<CustomObject>
    <label>Postal Code Assignment</label>
    <nameField>
        <displayFormat>PCA-{0000000000}</displayFormat>
        <label>Postal Code Assignment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Postal Code Assignments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Postal_Code_Assignment__c/fields/Role__c.field-meta.xml
<CustomField>
    <fullName>Role__c</fullName>
    <label>Role</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Raico_Roles</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Postal_Code_Assignment__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>PostalCodeAssignments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Postal_Code_Range__c/Postal_Code_Range__c.object-meta.xml
<CustomObject>
    <label>Postal Code Range</label>
    <nameField>
        <displayFormat>PCR-{0000000000}</displayFormat>
        <label>Postal Code Range Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Postal Code Ranges</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Postal_Code_Range__c/fields/Postal_Code_Start__c.field-meta.xml
<CustomField>
    <fullName>Postal_Code_Start__c</fullName>
    <label>Postal Code Start</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Postal_Code_Range__c/fields/PostalCodeAssignment__c.field-meta.xml
<CustomField>
    <fullName>PostalCodeAssignment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Postal Code Assignment</label>
    <referenceTo>Postal_Code_Assignment__c</referenceTo>
    <relationshipLabel>Postal Code Ranges</relationshipLabel>
    <relationshipName>PostalCodeRanges</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Postal_Code_Range__c/fields/PostalCodeEnd__c.field-meta.xml
<CustomField>
    <fullName>PostalCodeEnd__c</fullName>
    <label>Postal Code End</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Role_Assignment__c/Role_Assignment__c.object-meta.xml
<CustomObject>
    <label>Role Assignment</label>
    <nameField>
        <displayFormat>RA-{0000000000}</displayFormat>
        <label>Role Assignment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Role Assignments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Role_Assignment__c/fields/Additional_Roles__c.field-meta.xml
<CustomField>
    <fullName>Additional_Roles__c</fullName>
    <label>Additional Roles</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Raico_Roles</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Role_Assignment__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>RaicoCountries</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Role_Assignment__c/fields/Objecttype__c.field-meta.xml
<CustomField>
    <fullName>Objecttype__c</fullName>
    <label>Objecttype</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Account</fullName>
            </value>
            <value>
                <fullName>Building Project</fullName>
                <isActive>false</isActive>
                <label>Building Project</label>
            </value>
            <value>
                <fullName>Opportunity</fullName>
                <isActive>false</isActive>
                <label>Opportunity</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Role_Assignment__c/fields/PrimaryRole__c.field-meta.xml
<CustomField>
    <fullName>PrimaryRole__c</fullName>
    <label>Primary Role</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Raico_Roles</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Role_Assignment__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Account</fullName>
            </value>
            <value>
                <fullName>Fabricator</fullName>
            </value>
            <value>
                <fullName>Architect</fullName>
                <isActive>false</isActive>
                <label>Architect</label>
            </value>
            <value>
                <fullName>Planner</fullName>
                <isActive>false</isActive>
                <label>Planner</label>
            </value>
            <value>
                <fullName>Processor</fullName>
                <isActive>false</isActive>
                <label>Processor</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/User/fields/Comarch_External_UserID__c.field-meta.xml
<CustomField>
    <fullName>Comarch_External_UserID__c</fullName>
    <externalId>true</externalId>
    <label>Comarch External UserID</label>
    <length>40</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/globalValueSets/Raico_Roles.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Inside Sales</fullName>
    </customValue>
    <customValue>
        <fullName>Project Sales</fullName>
    </customValue>
    <customValue>
        <fullName>Sales</fullName>
    </customValue>
    <masterLabel>Raico Roles</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/RaicoCountries.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>AT</fullName>
    </customValue>
    <customValue>
        <fullName>CH</fullName>
    </customValue>
    <customValue>
        <fullName>DE</fullName>
    </customValue>
    <customValue>
        <fullName>FR</fullName>
    </customValue>
    <customValue>
        <fullName>IT</fullName>
    </customValue>
    <customValue>
        <fullName>BG</fullName>
    </customValue>
    <customValue>
        <fullName>BA</fullName>
    </customValue>
    <customValue>
        <fullName>XK</fullName>
    </customValue>
    <customValue>
        <fullName>MD</fullName>
    </customValue>
    <customValue>
        <fullName>HR</fullName>
    </customValue>
    <customValue>
        <fullName>ME</fullName>
    </customValue>
    <customValue>
        <fullName>RO</fullName>
    </customValue>
    <customValue>
        <fullName>RS</fullName>
    </customValue>
    <customValue>
        <fullName>SI</fullName>
    </customValue>
    <customValue>
        <fullName>NL</fullName>
    </customValue>
    <customValue>
        <fullName>UK</fullName>
    </customValue>
    <customValue>
        <fullName>GB</fullName>
    </customValue>
    <masterLabel>Raico Countries</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/V11_AccountOwnerAssignerTest.cls
@isTest
public class V11_AccountOwnerAssignerTest {

    @TestSetup
    static void makeData(){

        Profile p = [select id from profile where name ='System Administrator'][0];

        User u = new User();
        u.LastName = 'alias1';
        u.UserName = 'testuser@raico.de';
        u.Email = 'test@raico.de';
        u.alias = 'alias1';
        u.TimeZoneSidKey = 'Europe/Berlin';
        u.LocaleSidKey = 'de_DE_EURO';
        u.EmailEncodingKey = 'ISO-8859-1';
        u.ProfileId = p.Id;
        u.LanguageLocaleKey = 'de';
        u.Comarch_External_UserID__c = '123456';
        insert u;

        User u1 = new User();
        u1.LastName = 'alias2';
        u1.UserName = 'testuser2@raico.de';
        u1.Email = 'test2@raico.de';
        u1.alias = 'alias2';
        u1.TimeZoneSidKey = 'Europe/Berlin';
        u1.LocaleSidKey = 'de_DE_EURO';
        u1.EmailEncodingKey = 'ISO-8859-1';
        u1.ProfileId = p.Id;
        u1.LanguageLocaleKey = 'de';
        u1.Comarch_External_UserID__c = '123457';

        insert u1;

        Role_Assignment__c ra = new Role_Assignment__c();
        ra.PrimaryRole__c = 'Sales';
        ra.Additional_Roles__c = 'Project Sales';
        ra.Objecttype__c = 'Account';
        ra.Type__c = 'Account';

        insert ra;

        Postal_Code_Assignment__c pca = new Postal_Code_Assignment__c();
        pca.Role__c = 'Sales';
        pca.User__c = u.Id;
        pca.Country__c = 'DE';

        insert pca;

        Postal_Code_Assignment__c pca1 = new Postal_Code_Assignment__c();
        pca1.Role__c = 'Project Sales';
        pca1.User__c = u1.Id;
        pca1.Country__c = 'DE';

        insert pca1;

        Postal_Code_Range__c pcr = new Postal_Code_Range__c();
        pcr.Postal_Code_Start__c = 0;
        pcr.PostalCodeEnd__c = 99999;
        pcr.PostalCodeAssignment__c = pca.Id;

        insert pcr;

        
        Postal_Code_Range__c pcr1 = new Postal_Code_Range__c();
        pcr1.Postal_Code_Start__c = 0;
        pcr1.PostalCodeEnd__c = 99999;
        pcr1.PostalCodeAssignment__c = pca1.Id;

        insert pcr1;

        Account acc = new Account();
        Account_Template__c temp = new Account_Template__c();
        temp.Key__c ='1000';
        insert temp;

        acc.Name = 'Test';
        acc.Account_Template__c = temp.Id;
        acc.ComarchAccountNumber__c = '123';
        acc.BillingStreet = 'Test Street 1';
        acc.BillingCity = 'Testtown';
        acc.BillingPostalCode = '12345';
        acc.BillingCountryCode = 'DE';
        Database.insert(acc);

        Contact c = new Contact();
        c.ExternalComarchContactId__c = '123';
        c.AccountId = acc.Id;
        c.Salutation = 'Ms.';
        c.Title__c = 'ArchitektIn';
        c.LastName = 'Test';
        c.FirstName = 'hm';
        c.MiddleName = 'Lol';
        c.MobilePhone = '+491234';
        c.Phone = '+491234';
        c.Email = 'test@test.com';
        c.Language__c = 'de';

        Database.insert(c);



    }

    static testmethod void testAccounOwnerUodate(){

        Account acc = [SELECT Id FROM Account WHERE Name ='Test'];
        
        Test.startTest();
        V11_AccountOwnerUpdate.updateAccountOwner(acc.Id);
        test.stopTest();

    }
}