force-app/main/default/objects/Account/fields/Account_Template__c.field-meta.xml
<CustomField>
    <fullName>Account_Template__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>2000 - Customer, third country except Switzerland English-speaking

2001 - Customer, third country except Switzerland German-speaking

2002 - Customer, third country except Switzerland French-speaking

2010 - Customer, Switzerland German-speaking

2020 - Customer, Switzerland French-speaking

2030 - Customer, Switzerland English-speaking

3000 - Customer, EU except FR English-speaking

3001 - Customer, EU except FR German-speaking

Translated with www.DeepL.com/Translator (free version)</inlineHelpText>
    <label>Account Template</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account_Template__c.Name</field>
            <operation>notEqual</operation>
            <value>Migrated Account</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Account_Template__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/ComarchAccountNumber__c.field-meta.xml
<CustomField>
    <fullName>ComarchAccountNumber__c</fullName>
    <externalId>true</externalId>
    <label>Comarch Account Number</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/fields/Language__c.field-meta.xml
<CustomField>
    <fullName>Language__c</fullName>
    <label>Language</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>de</fullName>
            </value>
            <value>
                <fullName>it</fullName>
            </value>
            <value>
                <fullName>fr</fullName>
            </value>
            <value>
                <fullName>en</fullName>
            </value>
            <value>
                <fullName>es</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/TenderType__c.field-meta.xml
<CustomField>
    <fullName>TenderType__c</fullName>
    <label>Tender Type</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Competitive bidding</fullName>
            </value>
            <value>
                <fullName>GC</fullName>
            </value>
            <value>
                <fullName>Public</fullName>
            </value>
            <value>
                <fullName>Restricted</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Account.recordType-meta.xml
<RecordType>
    <fullName>Account</fullName>
    <active>true</active>
    <label>Account</label>
</RecordType>

force-app/main/default/objects/Account/recordTypes/Fabricator.recordType-meta.xml
<RecordType>
    <fullName>Fabricator</fullName>
    <active>true</active>
    <label>Fabricator</label>
</RecordType>

force-app/main/default/objects/BuildingProject__c/BuildingProject__c.object-meta.xml
<CustomObject>
    <label>Bauvorhaben</label>
    <nameField>
        <label>Building Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Bauvorhaben</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/BuildingProject__c/fields/AwardDate__c.field-meta.xml
<CustomField>
    <fullName>AwardDate__c</fullName>
    <label>Award Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/BuildingProject__c/fields/BuildingType__c.field-meta.xml
<CustomField>
    <fullName>BuildingType__c</fullName>
    <label>Building Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Culture</fullName>
            </value>
            <value>
                <fullName>Education</fullName>
            </value>
            <value>
                <fullName>Habitation</fullName>
            </value>
            <value>
                <fullName>Industrial and trade</fullName>
            </value>
            <value>
                <fullName>Office and administration</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Sport</fullName>
            </value>
            <value>
                <fullName>care and health</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/BuildingProject__c/fields/ConstructionEndPlanned__c.field-meta.xml
<CustomField>
    <fullName>ConstructionEndPlanned__c</fullName>
    <label>Construction End Planned</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/BuildingProject__c/fields/DateOfServiceSpecification__c.field-meta.xml
<CustomField>
    <fullName>DateOfServiceSpecification__c</fullName>
    <label>Date of Service Specification (est.)</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/BuildingProject__c/fields/ExternalNote__c.field-meta.xml
<CustomField>
    <fullName>ExternalNote__c</fullName>
    <label>External Note</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/BuildingProject__c/fields/LeadSource__c.field-meta.xml
<CustomField>
    <fullName>LeadSource__c</fullName>
    <label>Lead Source</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Architekturwettbewerb</fullName>
            </value>
            <value>
                <fullName>Construction site</fullName>
            </value>
            <value>
                <fullName>DOCUmedia</fullName>
            </value>
            <value>
                <fullName>Documedia CH</fullName>
            </value>
            <value>
                <fullName>Email</fullName>
            </value>
            <value>
                <fullName>iBau</fullName>
            </value>
            <value>
                <fullName>Own research</fullName>
            </value>
            <value>
                <fullName>Personal network</fullName>
            </value>
            <value>
                <fullName>Phone call</fullName>
            </value>
            <value>
                <fullName>SIMAP</fullName>
            </value>
            <value>
                <fullName>TED</fullName>
            </value>
            <value>
                <fullName>Vergabe24</fullName>
            </value>
            <value>
                <fullName>vip Network</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/BuildingProject__c/fields/Material__c.field-meta.xml
<CustomField>
    <fullName>Material__c</fullName>
    <label>Material</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Aluminium</fullName>
            </value>
            <value>
                <fullName>Steel</fullName>
            </value>
            <value>
                <fullName>Timber</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/BuildingProject__c/fields/NonDisclosureAgreement__c.field-meta.xml
<CustomField>
    <fullName>NonDisclosureAgreement__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Non Disclosure Agreement</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/BuildingProject__c/fields/OrderEntry__c.field-meta.xml
<CustomField>
    <fullName>OrderEntry__c</fullName>
    <label>Order Entry</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/BuildingProject__c/fields/ProjectPreview__c.field-meta.xml
<CustomField>
    <fullName>ProjectPreview__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Project preview</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/BuildingProject__c/fields/ProjectPriority__c.field-meta.xml
<CustomField>
    <fullName>ProjectPriority__c</fullName>
    <label>Project Priority</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Key Project</fullName>
            </value>
            <value>
                <fullName>Prio A</fullName>
            </value>
            <value>
                <fullName>Prio B</fullName>
            </value>
            <value>
                <fullName>Prio C</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/BuildingProject__c/fields/ProjectSupported__c.field-meta.xml
<CustomField>
    <fullName>ProjectSupported__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Project supported</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/BuildingProject__c/fields/Stage__c.field-meta.xml
<CustomField>
    <fullName>Stage__c</fullName>
    <label>Stage</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Research</fullName>
                <default>true</default>
                <label>Research</label>
            </value>
            <value>
                <fullName>Consulting/ Planning</fullName>
            </value>
            <value>
                <fullName>Tender &amp; Quote</fullName>
            </value>
            <value>
                <fullName>Award Fabricator</fullName>
            </value>
            <value>
                <fullName>Award System house</fullName>
            </value>
            <value>
                <fullName>Execution</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
                <label>Completed</label>
            </value>
            <value>
                <fullName>Award</fullName>
                <isActive>false</isActive>
                <label>Award</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/BuildingProject__c/fields/SubmissionDate__c.field-meta.xml
<CustomField>
    <fullName>SubmissionDate__c</fullName>
    <label>Submission Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/BuildingProject__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Extension</fullName>
            </value>
            <value>
                <fullName>New construction</fullName>
            </value>
            <value>
                <fullName>Renovation</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Comarch_Number__c/Comarch_Number__c.object-meta.xml
<CustomObject>
    <label>Comarch Number</label>
    <nameField>
        <label>Comarch Number Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Comarch Numbers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Comarch_Number__c/fields/Comarch_Number__c.field-meta.xml
<CustomField>
    <fullName>Comarch_Number__c</fullName>
    <label>Comarch Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Comarch_Number__c/fields/Comarch_Number_Prefix__c.field-meta.xml
<CustomField>
    <fullName>Comarch_Number_Prefix__c</fullName>
    <label>Comarch Number Prefix</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Comarch_Number__c/fields/Object__c.field-meta.xml
<CustomField>
    <fullName>Object__c</fullName>
    <label>Object</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Account</fullName>
            </value>
            <value>
                <fullName>Contact</fullName>
            </value>
            <value>
                <fullName>Building Project</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <formula>BuildingProject__r.Amount__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/BuildingProject__c.field-meta.xml
<CustomField>
    <fullName>BuildingProject__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Building Project</label>
    <referenceTo>BuildingProject__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/ProjectPriority__c.field-meta.xml
<CustomField>
    <fullName>ProjectPriority__c</fullName>
    <label>Project Priority</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Key Object KAM</fullName>
            </value>
            <value>
                <fullName>Prio A</fullName>
            </value>
            <value>
                <fullName>Prio B</fullName>
            </value>
            <value>
                <fullName>Prio C</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/recordTypes/Opportunity.recordType-meta.xml
<RecordType>
    <fullName>Opportunity</fullName>
    <active>true</active>
    <businessProcess>Opportunity</businessProcess>
    <label>Opportunity</label>
</RecordType>

force-app/main/default/objects/User/fields/Comarch_External_UserID__c.field-meta.xml
<CustomField>
    <fullName>Comarch_External_UserID__c</fullName>
    <externalId>true</externalId>
    <label>Comarch External UserID</label>
    <length>40</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/V11_BuildingProjectTriggerTest.cls
@isTest
public class V11_BuildingProjectTriggerTest {
    @TestSetup
    static void makeData(){

        Test.setMock(HttpCalloutMock.class, new V11_WebServiceMock());
        Database.DMLOptions dml = new Database.DMLOptions();
        dml.DuplicateRuleHeader.allowSave = true;
        dml.DuplicateRuleHeader.runAsCurrentUser = true; 

        Profile p = [select id from profile where name ='System Administrator'][0];

        User u = new User();
        u.LastName = 'alias1';
        u.UserName = 'testuser@raico.de';
        u.Email = 'test@raico.de';
        u.alias = 'alias1';
        u.TimeZoneSidKey = 'Europe/Berlin';
        u.LocaleSidKey = 'de_DE_EURO';
        u.EmailEncodingKey = 'ISO-8859-1';
        u.ProfileId = p.Id;
        u.LanguageLocaleKey = 'de';
        u.Comarch_External_UserID__c = '123456';
        insert u;

        List<Comarch_Number__c> cNumbers = new List<Comarch_Number__c>();

        Comarch_Number__c numberAcc = new Comarch_Number__c();
        numberAcc.Comarch_Number_Prefix__c = '';
        numberAcc.Comarch_Number__c = '123';
        numberAcc.Object__c = 'Account';
        cNumbers.add(numberAcc);


        Comarch_Number__c numberBP = new Comarch_Number__c();
        numberBP.Comarch_Number_Prefix__c = 'VS';
        numberBP.Comarch_Number__c = '123';
        numberBP.Object__c = 'Building Project';
        cNumbers.add(numberBP);

        insert cNumbers;

        Account_Template__c temp = new Account_Template__c();
        temp.Key__c ='1000';
        insert temp;


        Account acc = new Account();

        acc.Name = 'RAICO';
        acc.Account_Template__c = temp.Id;
        acc.ComarchAccountNumber__c = '1';
        acc.BillingStreet = 'Test Street 1';
        acc.BillingCity = 'Testtown';
        acc.BillingPostalCode = '12345';
        acc.BillingCountryCode = 'DE';
        acc.Language__c = 'DE';
        acc.Type = 'Competitor';
        Test.setMock(HttpCalloutMock.class, new V11_WebServiceMock());
        Database.insert(acc,dml);
        Test.setMock(HttpCalloutMock.class, new V11_WebServiceMock());

        Account acc1 = new Account();
        acc1.Name = 'Test Fabricator';
        acc.ComarchAccountNumber__c = '2';
        acc1.Account_Template__c = temp.Id;
        acc1.BillingStreet = 'Muster straße';
        acc1.BillingCity = 'Testn';
        acc1.BillingPostalCode = '12335';
        acc1.BillingCountryCode = 'DE';
        acc1.Language__c = 'DE';
        Test.setMock(HttpCalloutMock.class, new V11_WebServiceMock());
        Database.insert(acc1,dml);
        Test.setMock(HttpCalloutMock.class, new V11_WebServiceMock());

        BuildingProject__c bp = new BuildingProject__c();

        bp.Name='Test Automation';
        bp.Amount__c=12300000;
        bp.ProjectSupported__c=true;
        bp.AwardDate__c=Date.today()+10;
        bp.BuildingType__c='Culture';
        bp.ConstructionEndPlanned__c=Date.today()+10;
        bp.DateOfServiceSpecification__c=Date.today()+10;
        bp.ExternalNote__c='fghfgh';
        bp.LeadSource__c='Construction site';
        bp.Material__c='Aluminium';
        bp.NonDisclosureAgreement__c=true;
        bp.OrderEntry__c=Date.today()+10;
        bp.ProjectAddress__Street__s='Pettenkoferstraße 13';
        bp.ProjectAddress__City__s='Berlin';
        bp.ProjectAddress__PostalCode__s='10247';
        bp.ProjectAddress__CountryCode__s='DE';
        bp.ProjectPreview__c=true;
        bp.ProjectPriority__c='Prio A';
        bp.Stage__c='Research';
        bp.SubmissionDate__c=Date.today()+10;
        bp.TenderType__c='Competitive bidding';
        bp.TotalSize__c=123;
        bp.Type__c='New construction';
        bp.ConstructionStart__c=Date.today()+10;
        bp.RAICOSpecification__c=true;
        bp.ComarchBuildingProjectNumber__c='VS00000128';
        bp.BidderListSent__c=true;
        bp.ComarchSyncStatus__c='Success';
        bp.Service_specifications_sent__c=false;
        bp.Probability__c='0';

        Insert bp;

        Opportunity opp = new Opportunity();
        opp.StageName = 'Open';
        opp.Name = 'Test';
        opp.AccountId = acc1.Id;
        opp.BuildingProject__c = bp.Id;
        opp.CloseDate = Date.today();

        Insert opp;

        Opportunity opp2 = new Opportunity();
        opp2.StageName = 'Open';
        opp2.Name = 'Test Lose';
        opp2.AccountId = acc.Id;
        opp2.BuildingProject__c = bp.Id;
        opp2.CloseDate = Date.today();

        Insert opp2;

        Quote q = new Quote();
        q.OpportunityId = opp.Id;
        q.ParentOpportunity__c = opp.Id;
        q.Name = 'Test Quote';
        Insert q;
        
    }

    static testmethod void testTenderAndQuote(){
        Database.DMLOptions dml = new Database.DMLOptions();
        dml.DuplicateRuleHeader.allowSave = true;
        dml.DuplicateRuleHeader.runAsCurrentUser = true; 
        BuildingProject__c bp = [SELECT Id FROM BuildingProject__c WHERE Name='Test Automation'];
        bp.Service_specifications_sent__c = true;
        Test.startTest();
        Database.Update(bp,dml);
        Test.stopTest();
    }
    static testmethod void testExecutionSuccess(){
        BuildingProject__c bp = [SELECT Id FROM BuildingProject__c WHERE Name='Test Automation'];
        Account acc = [SELECT Id FROM Account WHERE Name='Test Fabricator'];
        bp.Allocationfabricator__c = acc.Id;
        bp.Probability__c = '100';
        Test.startTest();
        Update bp;
        Test.stopTest();
    }

    static testmethod void testCloseBP(){
        BuildingProject__c bp = [SELECT Id FROM BuildingProject__c WHERE Name='Test Automation'];
        bp.Stage__c = 'Closed';
        bp.Closing_Reason__c = 'Lost';
        Test.startTest();
        Update bp;
        Test.stopTest();
    }

    static testmethod void testWinOpp(){
        Opportunity opp = [SELECT Id FROM Opportunity WHERE Name='Test'];
        opp.StageName = 'Closed Won';
        Test.startTest();
        Update opp;
        Test.stopTest();
    }

    static testmethod void testQuote(){
        Quote q = [SELECT Id FROM Quote WHERE Name='Test Quote'];
        q.Status = 'Accepted';
        Test.startTest();
        Update q;
        Test.stopTest();
    }
}