force-app/main/default/objects/Account/fields/ComarchAccountNumber__c.field-meta.xml
<CustomField>
    <fullName>ComarchAccountNumber__c</fullName>
    <externalId>true</externalId>
    <label>Comarch Account Number</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Account.recordType-meta.xml
<RecordType>
    <fullName>Account</fullName>
    <active>true</active>
    <label>Account</label>
</RecordType>

force-app/main/default/objects/BuildingProject__c/BuildingProject__c.object-meta.xml
<CustomObject>
    <label>Bauvorhaben</label>
    <nameField>
        <label>Building Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Bauvorhaben</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/BuildingProject__c/fields/ComarchBuildingProjectNumber__c.field-meta.xml
<CustomField>
    <fullName>ComarchBuildingProjectNumber__c</fullName>
    <externalId>true</externalId>
    <label>Comarch Building Project Number</label>
    <length>40</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Contact/fields/ExternalComarchContactId__c.field-meta.xml
<CustomField>
    <fullName>ExternalComarchContactId__c</fullName>
    <externalId>true</externalId>
    <label>Comarch Contact Number</label>
    <length>20</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/InboundCall__c/InboundCall__c.object-meta.xml
<CustomObject>
    <label>Inbound Call</label>
    <nameField>
        <displayFormat>IC-{0000000000}</displayFormat>
        <label>Inbound Call Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Inbound Calls</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/InboundCall__c/fields/Data_2__c.field-meta.xml
<CustomField>
    <fullName>Data_2__c</fullName>
    <label>Data 2</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/InboundCall__c/fields/Data_3__c.field-meta.xml
<CustomField>
    <fullName>Data_3__c</fullName>
    <label>Data 3</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/InboundCall__c/fields/Data_4__c.field-meta.xml
<CustomField>
    <fullName>Data_4__c</fullName>
    <label>Data 4</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/InboundCall__c/fields/Outdated__c.field-meta.xml
<CustomField>
    <fullName>Outdated__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Outdated</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/InboundCall__c/fields/Webservice_Log__c.field-meta.xml
<CustomField>
    <fullName>Webservice_Log__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Webservice Log</label>
    <referenceTo>WebserviceLog__c</referenceTo>
    <relationshipLabel>Inbound Calls</relationshipLabel>
    <relationshipName>InboundCalls</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/BuildingProject__c.field-meta.xml
<CustomField>
    <fullName>BuildingProject__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Building Project</label>
    <referenceTo>BuildingProject__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/recordTypes/Opportunity.recordType-meta.xml
<RecordType>
    <fullName>Opportunity</fullName>
    <active>true</active>
    <businessProcess>Opportunity</businessProcess>
    <label>Opportunity</label>
</RecordType>

force-app/main/default/objects/Order/fields/Address__c.field-meta.xml
<CustomField>
    <fullName>Address__c</fullName>
    <label>Address</label>
    <length>300</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Order/fields/BuildingProject__c.field-meta.xml
<CustomField>
    <fullName>BuildingProject__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Building Project</label>
    <referenceTo>BuildingProject__c</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order/fields/ContactId__c.field-meta.xml
<CustomField>
    <fullName>ContactId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order/fields/Cost_of_goods__c.field-meta.xml
<CustomField>
    <fullName>Cost_of_goods__c</fullName>
    <label>Cost of goods</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/fields/DeliveryConditions__c.field-meta.xml
<CustomField>
    <fullName>DeliveryConditions__c</fullName>
    <label>Delivery Conditions</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/fields/Gross_margin__c.field-meta.xml
<CustomField>
    <fullName>Gross_margin__c</fullName>
    <description>Deckungsbeitrag</description>
    <label>Gross margin</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Order/fields/GrossTotalWeight__c.field-meta.xml
<CustomField>
    <fullName>GrossTotalWeight__c</fullName>
    <label>Gross Total Weight</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Order/fields/GrossValue__c.field-meta.xml
<CustomField>
    <fullName>GrossValue__c</fullName>
    <label>Gross Value</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Order/fields/Information__c.field-meta.xml
<CustomField>
    <fullName>Information__c</fullName>
    <label>Information</label>
    <length>130000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Order/fields/NetTotal__c.field-meta.xml
<CustomField>
    <fullName>NetTotal__c</fullName>
    <label>Net Total</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Order/fields/OrderType__c.field-meta.xml
<CustomField>
    <fullName>OrderType__c</fullName>
    <label>Order Type</label>
    <length>155</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/fields/PaymentCondition__c.field-meta.xml
<CustomField>
    <fullName>PaymentCondition__c</fullName>
    <label>Payment Condition</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/fields/Percent1__c.field-meta.xml
<CustomField>
    <fullName>Percent1__c</fullName>
    <label>Percent 1</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Order/fields/Percent2__c.field-meta.xml
<CustomField>
    <fullName>Percent2__c</fullName>
    <label>Percent 2</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Order/fields/Percent3__c.field-meta.xml
<CustomField>
    <fullName>Percent3__c</fullName>
    <label>Percent 3</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Order/fields/Percent4__c.field-meta.xml
<CustomField>
    <fullName>Percent4__c</fullName>
    <label>Percent 4</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Order/fields/Product_Group__c.field-meta.xml
<CustomField>
    <fullName>Product_Group__c</fullName>
    <label>Product Group</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/fields/Responsible_Employee__c.field-meta.xml
<CustomField>
    <fullName>Responsible_Employee__c</fullName>
    <label>Responsible Employee</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/fields/SalesRepresentative__c.field-meta.xml
<CustomField>
    <fullName>SalesRepresentative__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sales Representative</label>
    <referenceTo>User</referenceTo>
    <relationshipName>SalesOrders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order/fields/ShippingConditions__c.field-meta.xml
<CustomField>
    <fullName>ShippingConditions__c</fullName>
    <label>Shipping Conditions</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/fields/ShippingRecipient__c.field-meta.xml
<CustomField>
    <fullName>ShippingRecipient__c</fullName>
    <label>Shipping Recipient</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Order/fields/Supervisor__c.field-meta.xml
<CustomField>
    <fullName>Supervisor__c</fullName>
    <description>The comarch field &quot;Betreuer&quot; of an order (Vertriebsauftrag).</description>
    <label>Supervisor</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <externalId>true</externalId>
    <label>External Id</label>
    <length>100</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Quote/fields/ContactId__c.field-meta.xml
<CustomField>
    <fullName>ContactId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Quotes</relationshipLabel>
    <relationshipName>Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quote/fields/External_Id__c.field-meta.xml
<CustomField>
    <fullName>External_Id__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>External Id</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Quote/fields/NetTotal__c.field-meta.xml
<CustomField>
    <fullName>NetTotal__c</fullName>
    <label>Net Total</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Quote/fields/NetTotalWeight__c.field-meta.xml
<CustomField>
    <fullName>NetTotalWeight__c</fullName>
    <label>Net Total Weight</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Percent1__c.field-meta.xml
<CustomField>
    <fullName>Percent1__c</fullName>
    <label>Percent 1</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Percent2__c.field-meta.xml
<CustomField>
    <fullName>Percent2__c</fullName>
    <label>Percent 2</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Percent3__c.field-meta.xml
<CustomField>
    <fullName>Percent3__c</fullName>
    <label>Percent 3</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Percent4__c.field-meta.xml
<CustomField>
    <fullName>Percent4__c</fullName>
    <label>Percent 4</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Quote/fields/PriceListing__c.field-meta.xml
<CustomField>
    <fullName>PriceListing__c</fullName>
    <label>Price Listing</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Responsible_employee__c.field-meta.xml
<CustomField>
    <fullName>Responsible_employee__c</fullName>
    <label>Responsible employee</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Supervisor__c.field-meta.xml
<CustomField>
    <fullName>Supervisor__c</fullName>
    <label>Supervisor</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User/fields/Comarch_External_UserID__c.field-meta.xml
<CustomField>
    <fullName>Comarch_External_UserID__c</fullName>
    <externalId>true</externalId>
    <label>Comarch External UserID</label>
    <length>40</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/WebserviceLog__c/WebserviceLog__c.object-meta.xml
<CustomObject>
    <label>Webservice Log</label>
    <nameField>
        <displayFormat>WSL-{0000000000}</displayFormat>
        <label>Webservice Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Webservice Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/V11_batchOrderUpsert.cls
global class V11_batchOrderUpsert implements Database.Batchable<V11_OrderExportData.SalesOrder>, Database.AllowsCallouts, Database.Stateful {

    Map<String,InboundCall__c> failedInboundCalls = new Map<String,InboundCall__c>();
    WebserviceLog__c wsLog;    
    List<V11_OrderExportData.SalesOrder> salesOrders = new List<V11_OrderExportData.SalesOrder>();
    List<InboundCall__c> ibcs = new List<InboundCall__c>();
    List<V11_OrderExportData.SalesOrder> orders;
    List<String> orderIds = new List<String>();

    Map<String,Opportunity> existingOpps = new Map<String,Opportunity>();
    Set<String> existingQuotes = new Set<String>();
    Set<String> activeUsers = new Set<String>();
    Set<String> existingContacts = new Set<String>();
    Set<String> existingBPs = new Set<String>();

    public V11_batchOrderUpsert(){}

    public V11_batchOrderUpsert(List<string> orderIds){
        this.orderIds = orderIds;
    }
    public V11_batchOrderUpsert(List<V11_OrderExportData.SalesOrder> orders){
        this.orders = orders;
        wsLog = new WebserviceLog__c();
    }

    public List<V11_OrderExportData.SalesOrder> start (Database.BatchableContext bc)
    {
        List<InboundCall__c> ibc = [Select Object_ID__C, Id FROM InboundCall__c WHERE Object__c ='Order' and Status__c ='Error' and Outdated__c = false];
        for(InboundCall__c call : ibc)
        {
            failedInboundCalls.put(call.Object_ID__C,call);
        }        

        if(orders == null){
            List<String> tempIds = new List<String>();
            tempIds.addAll(orderIds);
            string orderList = '';
            Integer counter = 0;
            for(string id :tempIds){
                if(counter>9){
                    break;
                }
                orderList = orderList + '\'' + id +'\',';
                orderIds.remove(0);
                counter++;
            }
            wsLog = new WebserviceLog__c();
            orders = V11_callComarchImport.importOrders(wsLog,orderList.substring(0,orderList.length()-1));
        }      
        List<String> OppIds = new List<String>();
        List<String> QuoteIds = new List<String>();
        List<String> ContactIds = new List<String>();
        List<String> bpIds = new List<String>();
        for(V11_OrderExportData.SalesOrder order:orders){
            if(order.customerData.CustomerPartner!=null&&order.Rai_Opportunity!=null){
                String extId = order.customerData.CustomerPartner.number_x+order.Rai_Opportunity.number_x;
                OppIds.add(extId);
            }
            if(order.CustomerProposal!=null){
                String extId = order.CustomerProposal.number_x;
                QuoteIds.add(extId);
            }
            if(order.customerData.CareOfPartner!=null){
                String extId = order.customerData.CareOfPartner.number_x;
                ContactIds.add(extId);
            }
            if(order.Rai_Opportunity != null){
                String extId = order.Rai_Opportunity.number_x;
                bpIds.add(extId);
            }

        }
        List<Quote> quotes = [SELECT ID,External_Id__c FROM Quote WHERE External_Id__c in :QuoteIds];
        List<Opportunity> opps = [SELECT ID,External_Id__c FROM Opportunity WHERE External_Id__c in :OppIds];
        List<User> users = [SELECT Comarch_External_UserID__c FROM User WHERE IsActive = true AND Comarch_External_UserID__c !=''];
        List<Contact> contacts = [SELECT ExternalComarchContactId__c FROM Contact WHERE ExternalComarchContactId__c in :ContactIds];
        List<BuildingProject__c> bps = [SELECT ComarchBuildingProjectNumber__c FROM BuildingProject__c WHERE ComarchBuildingProjectNumber__c in :bpIds];

        for(Opportunity opp :opps){
            existingOpps.put(opp.External_Id__c, opp);
        }
        for(Quote q : quotes){
            existingQuotes.add(q.External_Id__c);
        }
        for(User u : users){
            activeUsers.add(u.Comarch_External_UserID__c);
        }
        for(Contact c : contacts){
            existingContacts.add(c.ExternalComarchContactId__c);
        }
        for(BuildingProject__c b : bps){
            existingBPs.add(b.ComarchBuildingProjectNumber__c);
        }


        return orders;

    }

    
    public void execute(Database.BatchableContext bc, List<V11_OrderExportData.SalesOrder> scope)
    {

        List<InboundCall__c> inboundCalls = new List<InboundCall__c>();
        List<InboundCall__c> inboundCallsWithErrors = new List<InboundCall__c>();
        List<InboundCall__c> updateCalls = new List<InboundCall__c>();
        List<Order> orders = new List<Order>();
        List<OrderItem> orderItems = new List<OrderItem>();
        List<V11_OrderExportData.SalesOrder> salesOrdersTemp = new List<V11_OrderExportData.SalesOrder>();

        

        for(V11_OrderExportData.SalesOrder oed: scope)
        { 

            InboundCall__c inboundCall = new InboundCall__c();
            InboundCall__c updateCall = new InboundCall__c();
            inboundCall.Webservice_Log__c = wsLog.Id;
            Order order = new Order();
            List<OrderItem> oItems = new List<OrderItem>();
            

            if(failedInboundCalls.containsKey(oed.guid)){

                updateCall = failedInboundCalls.get(oed.guid);
                updateCall.Outdated__c = true;
                updateCalls.add(updateCall);
            }

                inboundCall.Object__c = 'Order';
                inboundCall.Status__c = 'Pending';
                inboundCall.Object_ID__C = oed.guid;
                String dataJSON = JSON.serialize(oed);
                if(dataJSON.length()>130000){
                    inboundCall.Data__c = dataJSON.substring(0, 130000);
                    if(dataJSON.length()>260000){
                        inboundCall.Data_2__c = dataJSON.substring(130000, 260000);
                        if(dataJSON.length()>390000){
                            inboundCall.Data_3__c = dataJSON.substring(260000, 390000);
                            if(dataJSON.length()>520000){
                                inboundCall.Data_4__c = dataJSON.substring(390000, 520000);
                            }else{
                                inboundCall.Data_4__c = dataJSON.substring(390000, dataJSON.length());
                            }
                        }else{
                            inboundCall.Data_3__c = dataJSON.substring(260000, dataJSON.length());
                        }
                    }else{
                        inboundCall.Data_2__c = dataJSON.substring(130000, dataJSON.length());
                    }
                }else{
                    inboundCall.Data__c = dataJSON.substring(0, dataJSON.length());
                }
                

            try{

                if(oed.customerData.CustomerPartner == null){
                    continue;
                }
                if(oed.customerData.CustomerPartner.number_x.startsWith('98')){
                    Account acc = new Account(ComarchAccountNumber__c = '910000');
                    order.Account = acc;
                }else{
                    Account acc = new Account(ComarchAccountNumber__c = oed.customerData.CustomerPartner.number_x);
                    order.Account = acc;
                }                

                if(oed.Rai_Opportunity != null){
                    if(existingBPs.contains(oed.Rai_Opportunity.number_x)){
                    BuildingProject__c bp = new BuildingProject__c(ComarchBuildingProjectNumber__c = oed.Rai_Opportunity.number_x);
                    order.BuildingProject__r = bp;
                    }
                    
                } 
                if(oed.Rai_Opportunity!=null){
                    if(existingOpps.containsKey(oed.customerData.CustomerPartner.number_x+oed.Rai_Opportunity.number_x)){
                        order.Opportunity = existingOpps.get(oed.customerData.CustomerPartner.number_x+oed.Rai_Opportunity.number_x);
                    }
                }             

                if(oed.CustomerProposal != null){

                    if(existingQuotes.contains(oed.CustomerProposal.number_x)){
                        Quote q = new Quote(External_Id__c=oed.CustomerProposal.number_x);
                        order.Quote = q;
                    }

                }
                if(oed.customerData.CareOfPartner != null){

                    if(existingContacts.contains(oed.customerData.CareOfPartner.number_x)){
                        Contact con = new Contact(ExternalComarchContactId__c = oed.customerData.CareOfPartner.number_x);
                        order.ContactId__r = con;
                    }


                }if(oed.SalesRepresentatives != null){

                    if(activeUsers.contains(oed.SalesRepresentatives[0].number_x)){
                        User u = new User(Comarch_External_UserID__c=oed.SalesRepresentatives[0].number_x);
                        order.SalesRepresentative__r =  u;
                    }

                }
                 //Außendienst

                
                order.Name = oed.number_x;
                order.ExternalId__c = oed.number_x;
                if(oed.Type_x_SalesOrder != null){order.OrderType__c = oed.Type_x_SalesOrder.code+ ' | '+ oed.Type_x_SalesOrder.description;}                
                order.Status = 'Draft';               
                order.EffectiveDate = date.newInstance(oed.date_x.year(), oed.date_x.month(), oed.date_x.day());
                
                order.Responsible_Employee__c = oed.ResponsiblePartner != null ? oed.ResponsiblePartner.name:''; //Zuständiger Mitarbeiter(Innendienst)
                
                order.Supervisor__c = oed.Rai_ResponsibleEmployee != null ? oed.Rai_ResponsibleEmployee.name:''; //Betreuer
                
                
                order.Product_Group__c = oed.classification1 != null ? oed.classification1.description : '';               
                order.Information__c = oed.rai_infoText;
                order.Description = oed.rai_objectName != null ? oed.rai_objectName:'';
                //Lieferempfänger (Reiter):
                order.ShippingRecipient__c = oed.deliveryCustomerData != null ? oed.deliveryCustomerData.name : '';

                if(oed.deliveryCustomerData.addressData!=null){
                    
                    /*order.ShippingStreet = oed.deliveryCustomerData.addressData.street;
                    order.ShippingCity = oed.deliveryCustomerData.addressData.city;
                    order.ShippingPostalCode = oed.deliveryCustomerData.addressData.postalCode;
                    order.ShippingCountryCode = oed.deliveryCustomerData.addressData.Country.isoCode;*/

                    String address = oed.deliveryCustomerData.addressData.street + '\n' + oed.deliveryCustomerData.addressData.postalCode + ' ' + oed.deliveryCustomerData.addressData.city + '\n' + oed.deliveryCustomerData.addressData.Country.isoCode;
                    order.Address__c = address;
                }


                //Lieferkonditionen (Reiter)
                order.DeliveryConditions__c = oed.deliveryData.DeliveryTerms != null ? oed.deliveryData.DeliveryTerms.description : '';
                order.ShippingConditions__c = oed.deliveryData.ShippingTerms != null ? oed.deliveryData.ShippingTerms.description : '';

                //Rechnungskonditionen (Reiter):
                order.PriceListing__c = oed.PriceListing != null ? oed.PriceListing.description : '';
                order.Percent1__c = Decimal.valueOf(oed.discounts[0].value);
                order.Percent2__c = Decimal.valueOf(oed.discounts[1].value);
                order.Percent3__c = Decimal.valueOf(oed.discounts[2].value);
                order.Percent4__c = Decimal.valueOf(oed.discounts[3].value);
                order.PaymentCondition__c = oed.InvoicingData.PaymentTerms!= null ? oed.InvoicingData.PaymentTerms.description : '';
                
      
                //Auftragswerte
                order.GrossValue__c = Decimal.valueOf(oed.totalValues.grossValue.amount);
                order.NetTotal__c = Decimal.valueOf(oed.totalValues.netValue.amount);
                order.Gross_margin__c = Decimal.valueOf(oed.grossMargin);
                order.Cost_of_goods__c = oed.costOfGoods.amount1;
                
                //Gewicht & Volumen
                order.GrossTotalWeight__c = Decimal.valueOf(oed.totalValues.grossWeight.amount);
                order.NetTotalWeight__c = Decimal.valueOf(oed.totalValues.netWeight.amount);
                


            

            }catch(Exception e){

                inboundCall.Status__c = 'Error';
                inboundCall.ErrorMessage__c = e.getLineNumber()+' '+ e.getMessage();                
                inboundCallsWithErrors.add(inboundCall);

            }
            if(inboundCall.Status__c == 'Pending'){

                inboundCalls.add(inboundCall);
                orders.add(order);
                orderItems.addAll(oItems);
                salesOrdersTemp.add(oed);

            }



        }
        Schema.SObjectField Idfield = Order.Fields.ExternalId__c;
        List<Database.UpsertResult> urList = Database.upsert(orders,Idfield,false);

        for(Integer index = 0, size = urList.size();index<size;index++)
        {
            if(!urList[index].success)
            {
                inboundCalls[index].Status__c = 'Error';
                String errorMessages ='';
                for(Database.Error error : urList[index].getErrors()){
                    errorMessages = errorMessages + '\n'+ error.message;
                }
                inboundCalls[index].ErrorMessage__c = errorMessages;
            }else
            {
                if(salesOrdersTemp[index].Details==null){
                    inboundCalls[index].Status__c = 'Success';
                    continue;
                }
                ibcs.add(inboundCalls[index]);
                salesOrders.add(salesOrdersTemp[index]);
            }            

        }
        inboundCalls.addAll(inboundCallsWithErrors);
        insert inboundCalls;
        update updateCalls;
    }

    public void finish(Database.BatchableContext bc)
    {
        V11_batchOrderUpsertPositions batchhandler = new V11_batchOrderUpsertPositions(salesOrders,ibcs,orderIds);
        database.executeBatch(batchhandler,200);

    }
}