force-app/main/default/objects/Account/fields/ComarchAccountNumber__c.field-meta.xml
<CustomField>
    <fullName>ComarchAccountNumber__c</fullName>
    <externalId>true</externalId>
    <label>Comarch Account Number</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Account.recordType-meta.xml
<RecordType>
    <fullName>Account</fullName>
    <active>true</active>
    <label>Account</label>
</RecordType>

force-app/main/default/objects/Bidder__c/Bidder__c.object-meta.xml
<CustomObject>
    <label>Bieter</label>
    <nameField>
        <label>Bidder Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Bieter</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Bidder__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Suggested For Bidder List</relationshipLabel>
    <relationshipName>Bidders</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Bidder__c/fields/Building_Project__c.field-meta.xml
<CustomField>
    <fullName>Building_Project__c</fullName>
    <label>Building Project</label>
    <referenceTo>BuildingProject__c</referenceTo>
    <relationshipName>Bidders</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Bidder__c/recordTypes/Raico_bidder.recordType-meta.xml
<RecordType>
    <fullName>Raico_bidder</fullName>
    <active>true</active>
    <label>Raico bidder</label>
</RecordType>

force-app/main/default/objects/BuildingProject__c/BuildingProject__c.object-meta.xml
<CustomObject>
    <label>Bauvorhaben</label>
    <nameField>
        <label>Building Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Bauvorhaben</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/BuildingProject__c/fields/BidderListSent__c.field-meta.xml
<CustomField>
    <fullName>BidderListSent__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Bidder list sent</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/BuildingProject__c/fields/ComarchBuildingProjectNumber__c.field-meta.xml
<CustomField>
    <fullName>ComarchBuildingProjectNumber__c</fullName>
    <externalId>true</externalId>
    <label>Comarch Building Project Number</label>
    <length>40</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/BuildingProject__c/fields/Stage__c.field-meta.xml
<CustomField>
    <fullName>Stage__c</fullName>
    <label>Stage</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Research</fullName>
                <default>true</default>
                <label>Research</label>
            </value>
            <value>
                <fullName>Consulting/ Planning</fullName>
            </value>
            <value>
                <fullName>Tender &amp; Quote</fullName>
            </value>
            <value>
                <fullName>Award Fabricator</fullName>
            </value>
            <value>
                <fullName>Award System house</fullName>
            </value>
            <value>
                <fullName>Execution</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
                <label>Completed</label>
            </value>
            <value>
                <fullName>Award</fullName>
                <isActive>false</isActive>
                <label>Award</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/V11_BidderTriggerTest.cls
@istest
private class V11_BidderTriggerTest {
    
    static testmethod void BidderTriggerTest()
    {        
        RecordType rt = [SELECT Id FROM RecordType WHERE DeveloperName = 'Raico_bidder'];
        String rty = rt.Id;
        Account a = new Account();
        a.Name = 'test3';
        a.Type = 'Architect';
        a.ComarchAccountNumber__c = 'test1';
        a.BillingStreet = 'Test Street 1';
        a.BillingCity = 'Testtown';
        a.BillingPostalCode = '12345';
        a.BillingCountryCode = 'DE';
        insert a;
        
        BuildingProject__c bp = new BuildingProject__c();
        bp.Name = 'test';
        bp.Amount__c = 123;
        bp.Stage__c = 'Research';
        bp.ComarchBuildingProjectNumber__c = 'Test';
        bp.ProjectAddress__Street__s = 'Pettenkoferstraße 13';
        bp.ProjectAddress__City__s = 'Berlin';
        bp.ProjectAddress__PostalCode__s = '10247';
        bp.ProjectAddress__CountryCode__s = 'DE';
        bp.BidderListSent__c = true;
        insert bp;


        Bidder__c b = new Bidder__c();
        b.Name = 'TEST123';
        b.RecordTypeId = rty;
        b.Account__c = a.Id;
        b.Building_Project__c = bp.Id;
        insert b;
        
        try {
            delete b;
            System.assert(false, 'Bidder__c record should not be deleted');
        } catch (DmlException ex) {
            System.assert(ex.getMessage().contains(Label.BidderDeletionErr), 'Expected error message not found');
        }
        
    }

}