force-app/main/default/objects/Account/fields/ComarchAccountNumber__c.field-meta.xml
<CustomField>
    <fullName>ComarchAccountNumber__c</fullName>
    <externalId>true</externalId>
    <label>Comarch Account Number</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Account.recordType-meta.xml
<RecordType>
    <fullName>Account</fullName>
    <active>true</active>
    <label>Account</label>
</RecordType>

force-app/main/default/objects/BuildingProject__c/BuildingProject__c.object-meta.xml
<CustomObject>
    <label>Bauvorhaben</label>
    <nameField>
        <label>Building Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Bauvorhaben</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/BuildingProject__c/fields/ComarchBuildingProjectNumber__c.field-meta.xml
<CustomField>
    <fullName>ComarchBuildingProjectNumber__c</fullName>
    <externalId>true</externalId>
    <label>Comarch Building Project Number</label>
    <length>40</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Contact/fields/ExternalComarchContactId__c.field-meta.xml
<CustomField>
    <fullName>ExternalComarchContactId__c</fullName>
    <externalId>true</externalId>
    <label>Comarch Contact Number</label>
    <length>20</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/InboundCall__c/InboundCall__c.object-meta.xml
<CustomObject>
    <label>Inbound Call</label>
    <nameField>
        <displayFormat>IC-{0000000000}</displayFormat>
        <label>Inbound Call Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Inbound Calls</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Opportunity/fields/BuildingProject__c.field-meta.xml
<CustomField>
    <fullName>BuildingProject__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Building Project</label>
    <referenceTo>BuildingProject__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/ParentOpportunity__c.field-meta.xml
<CustomField>
    <fullName>ParentOpportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>BP Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/ResubmissionDate__c.field-meta.xml
<CustomField>
    <fullName>ResubmissionDate__c</fullName>
    <label>Resubmission Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/recordTypes/Opportunity.recordType-meta.xml
<RecordType>
    <fullName>Opportunity</fullName>
    <active>true</active>
    <businessProcess>Opportunity</businessProcess>
    <label>Opportunity</label>
</RecordType>

force-app/main/default/objects/Quote/fields/AccountId__c.field-meta.xml
<CustomField>
    <fullName>AccountId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Quotes</relationshipLabel>
    <relationshipName>Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quote/fields/BuildingProjectName__c.field-meta.xml
<CustomField>
    <fullName>BuildingProjectName__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Building Project</label>
    <referenceTo>BuildingProject__c</referenceTo>
    <relationshipLabel>Quotes</relationshipLabel>
    <relationshipName>Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quote/fields/ContactId__c.field-meta.xml
<CustomField>
    <fullName>ContactId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Quotes</relationshipLabel>
    <relationshipName>Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quote/fields/EntryDate__c.field-meta.xml
<CustomField>
    <fullName>EntryDate__c</fullName>
    <label>Entry Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Quote/fields/External_Id__c.field-meta.xml
<CustomField>
    <fullName>External_Id__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>External Id</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Quote/fields/Grand_Total__c.field-meta.xml
<CustomField>
    <fullName>Grand_Total__c</fullName>
    <label>Grand Totals</label>
    <precision>14</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Loss__c.field-meta.xml
<CustomField>
    <fullName>Loss__c</fullName>
    <label>Loss reason</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Status</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Delivery date</fullName>
            </value>
            <value>
                <fullName>Price</fullName>
            </value>
            <value>
                <fullName>Competition in tender</fullName>
            </value>
            <value>
                <fullName>Offer submission too long</fullName>
            </value>
            <value>
                <fullName>No suitable technical solution</fullName>
            </value>
            <value>
                <fullName>Replaced</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Quote/fields/Multi_quote__c.field-meta.xml
<CustomField>
    <fullName>Multi_quote__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Mehrfachangebot</description>
    <label>Multi quote</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Quote/fields/NetTotal__c.field-meta.xml
<CustomField>
    <fullName>NetTotal__c</fullName>
    <label>Net Total</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Quote/fields/ParentOpportunity__c.field-meta.xml
<CustomField>
    <fullName>ParentOpportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Building Project Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Building Project Quote</relationshipLabel>
    <relationshipName>Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Percent1__c.field-meta.xml
<CustomField>
    <fullName>Percent1__c</fullName>
    <label>Percent 1</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Percent2__c.field-meta.xml
<CustomField>
    <fullName>Percent2__c</fullName>
    <label>Percent 2</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Percent3__c.field-meta.xml
<CustomField>
    <fullName>Percent3__c</fullName>
    <label>Percent 3</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Percent4__c.field-meta.xml
<CustomField>
    <fullName>Percent4__c</fullName>
    <label>Percent 4</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Quote/fields/PriceListing__c.field-meta.xml
<CustomField>
    <fullName>PriceListing__c</fullName>
    <label>Price Listing</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Quote/fields/ProductGroup__c.field-meta.xml
<CustomField>
    <fullName>ProductGroup__c</fullName>
    <label>Product Group</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Quote/fields/QuoteNumber__c.field-meta.xml
<CustomField>
    <fullName>QuoteNumber__c</fullName>
    <label>Quote Number</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Responsible_employee__c.field-meta.xml
<CustomField>
    <fullName>Responsible_employee__c</fullName>
    <label>Responsible employee</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Quote/fields/SalesRepresentive__c.field-meta.xml
<CustomField>
    <fullName>SalesRepresentive__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sales Representive</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Quotes1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Supervisor__c.field-meta.xml
<CustomField>
    <fullName>Supervisor__c</fullName>
    <label>Supervisor</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Type_of_Quote__c.field-meta.xml
<CustomField>
    <fullName>Type_of_Quote__c</fullName>
    <label>Type of Quote</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User/fields/Comarch_External_UserID__c.field-meta.xml
<CustomField>
    <fullName>Comarch_External_UserID__c</fullName>
    <externalId>true</externalId>
    <label>Comarch External UserID</label>
    <length>40</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/V11_batchQuoteUpsertQuotes.cls
global class V11_batchQuoteUpsertQuotes implements Database.Batchable<V11_QuoteExportData.CustomerProposal>, Database.Stateful {

    List<V11_QuoteExportData.CustomerProposal> cProps;
    List<InboundCall__c> ibcs;
    Map<String,Opportunity> parentOppMap;

    Map<String,InboundCall__c> inboundCallsMap = new Map<String,InboundCall__c>();
    List<V11_QuoteExportData.CustomerProposal> cPropsPositions = new List<V11_QuoteExportData.CustomerProposal>();
    List<InboundCall__c> ibcsPositions = new List<InboundCall__c>();

    Map<String,String> existingQuotesWithOpps = new Map<String,String>();
    Set<String> existingContacts = new Set<String>();
    Set<String> existingAccounts = new Set<String>();
    Set<String> existingBPs = new Set<String>();
    Set<String> activeUsers = new Set<String>();

    public V11_batchQuoteUpsertQuotes(List<V11_QuoteExportData.CustomerProposal> cProps,List<InboundCall__c> ibcs,Map<String,Opportunity> parentOppMap){
        this.cProps = cProps;
        this.ibcs = ibcs;
        this.parentOppMap = parentOppMap;
    }





    public List<V11_QuoteExportData.CustomerProposal> start (Database.BatchableContext bc)
    {
        for(Integer index = 0, size = ibcs.size();index<size;index++){
            inboundCallsMap.put(cProps[index].guid,ibcs[index]);
        }
        List<String> contactIds = new List<String>();
        List<String> accIds = new List<String>();
        List<String> quoteIds = new List<String>();
        List<String> bpIds = new List<String>();
        for(V11_QuoteExportData.CustomerProposal q :cProps){
            quoteIds.add(q.number_x);
            if(q.customerData.CareOfPartner != null){
                contactIds.add(q.customerData.CareOfPartner.number_x);
            }
            if(q.customerData.CustomerPartner != null){
                accIds.add(q.customerData.CustomerPartner.number_x);
            }
            if(q.Rai_Opportunity != null){
                bpIds.add(q.Rai_Opportunity.number_x);
            }         
        }
        List<Quote> existingOpps = [SELECT OpportunityId, External_Id__c FROM Quote WHERE External_Id__c IN: quoteIds];
        for(Quote qOpps: existingOpps){
            existingQuotesWithOpps.put(qOpps.External_Id__c, qOpps.OpportunityId);
        }

        List<User> users = [SELECT Comarch_External_UserID__c FROM User WHERE IsActive = true];
        List<Contact> contacts = [SELECT ExternalComarchContactId__c FROM Contact WHERE ExternalComarchContactId__c in :contactIds];
        List<Account> accs = [SELECT ComarchAccountNumber__c FROM Account WHERE ComarchAccountNumber__c in :accIds];
        List<BuildingProject__c> bps = [SELECT ComarchBuildingProjectNumber__c FROM BuildingProject__c WHERE ComarchBuildingProjectNumber__c in :bpIds];

        for(User u : users){
            activeUsers.add(u.Comarch_External_UserID__c);
        }
        for(Contact c : contacts){
            existingContacts.add(c.ExternalComarchContactId__c);
        }
        for(Account a : accs){
            existingAccounts.add(a.ComarchAccountNumber__c);
        }
        for(BuildingProject__c b : bps){
            existingBPs.add(b.ComarchBuildingProjectNumber__c);
        }

        return cProps;

    }

    
    public void execute(Database.BatchableContext bc, List<V11_QuoteExportData.CustomerProposal> scope)
    {

        List<InboundCall__c> inboundCalls = new List<InboundCall__c>();
        List<InboundCall__c> inboundCallsWithErrors = new List<InboundCall__c>();
        List<InboundCall__c> updateCalls = new List<InboundCall__c>();
        List<Quote> quotes = new List<Quote>();
        List<V11_QuoteExportData.CustomerProposal> cPropsTemp = new List<V11_QuoteExportData.CustomerProposal>();
        List<Opportunity> childOpps = new List<Opportunity>();
        

        for(V11_QuoteExportData.CustomerProposal qed: scope)
        {
            if( qed.customerData.CustomerPartner.number_x ==''){
                continue;
            }
            
            Quote quote;           
            InboundCall__c ibc = inboundCallsMap.get(qed.guid);
            Opportunity childOpp;

            try{

                quote = new Quote(External_Id__c = qed.number_x);

                if(parentOppMap.containsKey(qed.number_x)){
                    
                    
                    Opportunity parentOpp = new Opportunity(External_Id__c = qed.customerData.CustomerPartner.number_x  + qed.Rai_Opportunity.number_x);
                    childOpp = parentOppMap.get(qed.number_x);
                    if(childOpp.External_Id__c != parentOpp.External_Id__c){
                        childOpp.ParentOpportunity__r = parentOpp;
                        quote.ParentOpportunity__r = parentOpp;
                    }
                    

                }else{

                    if(!existingQuotesWithOpps.containsKey(qed.number_x)){
                        Opportunity opp;

                        if(qed.Rai_Opportunity == null){
        
                                string extIdOpp = qed.customerData.CustomerPartner.number_x + qed.number_x;                  
                                opp = new Opportunity(External_Id__c = extIdOpp);
        
                            } 
                        else//Bauvorhaben
                        {
                            string extIdOpp = qed.customerData.CustomerPartner.number_x  + qed.Rai_Opportunity.number_x ;
                            opp = new Opportunity(External_Id__c = extIdOpp);
                            
                        }
                        quote.ParentOpportunity__r = opp;
                        quote.Opportunity = opp;
                    }  
                }   

                if(qed.customerData.CustomerPartner == null){
                    continue;
                }

                if(existingAccounts.contains(qed.customerData.CustomerPartner.number_x)){
                    Account acc = new Account (ComarchAccountNumber__c = qed.customerData.CustomerPartner.number_x);
                    quote.AccountId__r= acc; 
                }
              
                               
                if(qed.customerData.CareOfPartner != null){
                    if(existingContacts.contains(qed.customerData.CareOfPartner.number_x)){
                        Contact con = new Contact(ExternalComarchContactId__c = qed.customerData.CareOfPartner.number_x);
                        quote.ContactId__r = con;
                    }
                  
                }

                if(qed.SalesRepresentative_CustomerProposal != null){

                    if(activeUsers.contains(qed.SalesRepresentative_CustomerProposal.number_x)){
                        User us = new User(Comarch_External_UserID__c = qed.SalesRepresentative_CustomerProposal.number_x);
                        quote.SalesRepresentive__r = us;
                    }

                }
                if(qed.Rai_Opportunity != null){
                    if(existingBPs.contains(qed.Rai_Opportunity.number_x)){
                        BuildingProject__c bp = new BuildingProject__c(ComarchBuildingProjectNumber__c = qed.Rai_Opportunity.number_x);
                        quote.BuildingProjectName__r = bp;
                    }
                    
                }
               
                // Kopfdaten
                quote.Name = qed.number_x;
                quote.QuoteNumber__c = qed.number_x;
                
                quote.Type_of_Quote__c = qed.Type_x_CustomerProposal.description;         
                quote.Responsible_employee__c = qed.ResponsiblePartner.name;
                quote.Supervisor__c = qed.Rai_ResponsibleEmployee_CustomerProposal != null? qed.Rai_ResponsibleEmployee_CustomerProposal.name:'';
                quote.Information__c = qed.rai_infoText;
                quote.EntryDate__c = date.newInstance(qed.date_x.year(), qed.date_x.month(), qed.date_x.day());
                quote.ProductGroup__c = qed.classification1.description;
                quote.Description = qed.rai_objectName;

                if(qed.reviewDate.year() >= date.today().year()){
                    quote.ResubmissionDate__c = date.newInstance(qed.reviewDate.year(), qed.reviewDate.month(), qed.reviewDate.day()); 
                } else {
                    Date td = Date.today();
                    Date fd = td.addDays(7);
                    quote.ResubmissionDate__c = fd;
                }
                
                //Statusabfrage ob Angebot ersetzt
                
                if(qed.Classification3 != null){
                    if(qed.Classification3.code == '210' || qed.Classification3.code == '205'){
                        quote.Status = 'Rejected';
                        quote.Loss__c = 'Replaced';
                    }
                    else if(qed.totalValues.grossValue.amount == '0'){
                        quote.Status = 'Requested';
                        }else{
                        quote.Status = 'Sent';
                        }
                        
                }
                else{
                        if(qed.totalValues.grossValue.amount == '0'){
                        quote.Status = 'Requested';
                        }else{
                        quote.Status = 'Sent';
                        }
                        
                    } 
                
                
                
                //Rechnungskonditionen
                quote.PriceListing__c = qed.PriceListing != null? qed.PriceListing.description : '';
                quote.Percent1__c = Decimal.valueOf(qed.discounts[0].value);
                quote.Percent2__c = Decimal.valueOf(qed.discounts[1].value);
                quote.Percent3__c = Decimal.valueOf(qed.discounts[2].value);
                quote.Percent4__c = Decimal.valueOf(qed.discounts[3].value);
                quote.PaymentCondition__c = qed.InvoicingData.PaymentTerms.description;

                //Klassifikationen

                //quote.Multi_quote__c = 
                
               
                //Auftragswerte
                quote.GrossTotalWeight__c = Decimal.valueOf(qed.totalValues.grossWeight.amount);
                quote.Grand_Total__c = Decimal.valueOf(qed.totalValues.grossValue.amount);
                quote.NetTotal__c = Decimal.valueOf(qed.totalValues.netValue.amount);         

            }catch(Exception e){

                ibc.Status__c = 'Error';
                ibc.ErrorMessage__c = ' | C2 UpsertQuotes | '+ e.getLineNumber()+' | '+e.getMessage();
                inboundCallsWithErrors.add(ibc);

            }
            if(ibc.Status__c == 'Pending'){
                inboundCalls.add(ibc);
                quotes.add(quote);
                cPropsTemp.add(qed);
                if(childOpp != null){
                    if(childOpp.ParentOpportunity__c != null){
                        childOpps.add(childOpp);
                    }                    
                }
            }
        
    
        


        }


        Schema.SObjectField Idfield = Quote.Fields.External_Id__c;
        List<Database.UpsertResult> urList = Database.upsert(quotes,Idfield,false);


        for(Integer index = 0, size = urList.size();index<size;index++)
        {

            if(!urList[index].success)
            {
                inboundCalls[index].Status__c = 'Error';
                String errorMessages = '';
                for(Database.Error error : urList[index].getErrors()){
                    errorMessages = errorMessages + '\n'+ error.message;
                }
                inboundCalls[index].ErrorMessage__c = errorMessages;
            }else{
                if(cPropsTemp[index].Details==null){
                    inboundCalls[index].Status__c = 'Success';
                    continue;
                }
                ibcsPositions.add(inboundCalls[index]);
                cPropsPositions.add(cPropsTemp[index]);
            }                

        }
        inboundCalls.addAll(inboundCallsWithErrors);
        update inboundCalls;
        if(childOpps.size()>0){
                Set<Opportunity> oppSet = new Set<Opportunity>();
                List<Opportunity> finalOppList = new List<Opportunity>();
                    for (Opportunity o : childOpps) {
                        if (oppSet.add(o)) {
                            finalOppList.add(o);
                        }
                    }
            childOpps.clear();
            childOpps.addAll(finalOppList);
            update childOpps;
        }
        
    }

    global void finish(Database.BatchableContext bc)
    {
        V11_batchQuoteUpsertQuotesPositions batchhandler = new V11_batchQuoteUpsertQuotesPositions(cPropsPositions, ibcsPositions);
        database.executeBatch(batchhandler,200);

    }
}