force-app/main/default/objects/Account/fields/ComarchAccountNumber__c.field-meta.xml
<CustomField>
    <fullName>ComarchAccountNumber__c</fullName>
    <externalId>true</externalId>
    <label>Comarch Account Number</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Account.recordType-meta.xml
<RecordType>
    <fullName>Account</fullName>
    <active>true</active>
    <label>Account</label>
</RecordType>

force-app/main/default/objects/BuildingProject__c/BuildingProject__c.object-meta.xml
<CustomObject>
    <label>Bauvorhaben</label>
    <nameField>
        <label>Building Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Bauvorhaben</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/BuildingProject__c/fields/ComarchBuildingProjectNumber__c.field-meta.xml
<CustomField>
    <fullName>ComarchBuildingProjectNumber__c</fullName>
    <externalId>true</externalId>
    <label>Comarch Building Project Number</label>
    <length>40</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Comarch_Number__c/Comarch_Number__c.object-meta.xml
<CustomObject>
    <label>Comarch Number</label>
    <nameField>
        <label>Comarch Number Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Comarch Numbers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Comarch_Number__c/fields/Comarch_Number__c.field-meta.xml
<CustomField>
    <fullName>Comarch_Number__c</fullName>
    <label>Comarch Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Comarch_Number__c/fields/Comarch_Number_Prefix__c.field-meta.xml
<CustomField>
    <fullName>Comarch_Number_Prefix__c</fullName>
    <label>Comarch Number Prefix</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Comarch_Number__c/fields/Object__c.field-meta.xml
<CustomField>
    <fullName>Object__c</fullName>
    <label>Object</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Account</fullName>
            </value>
            <value>
                <fullName>Contact</fullName>
            </value>
            <value>
                <fullName>Building Project</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/ExternalComarchContactId__c.field-meta.xml
<CustomField>
    <fullName>ExternalComarchContactId__c</fullName>
    <externalId>true</externalId>
    <label>Comarch Contact Number</label>
    <length>20</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/V11_ComarchNumberManager.cls
public class V11_ComarchNumberManager {

    /*public static void setNumberBP(Id Id){
        BuildingProject__c bp = [SELECT Id,ComarchBuildingProjectNumber__c FROM BuildingProject__c WHERE Id=:Id];

        if(bp.ComarchBuildingProjectNumber__c ==''||bp.ComarchBuildingProjectNumber__c == null){
            bp.ComarchBuildingProjectNumber__c = getNumber('Building Project');
            Database.DMLOptions dml = new Database.DMLOptions();
            dml.DuplicateRuleHeader.allowSave = true;
            Database.Update(bp,dml);
        }

    }
    public static void setNumberAccount(Id Id){
        Account acc = [SELECT Id,ComarchAccountNumber__c FROM Account WHERE Id=:Id];

        if(acc.ComarchAccountNumber__c ==''||acc.ComarchAccountNumber__c == null){
            acc.ComarchAccountNumber__c = getNumber('Account');
            Database.DMLOptions dml = new Database.DMLOptions();
            dml.DuplicateRuleHeader.allowSave = true;
            Database.Update(acc,dml);
        }

    }
    public static void setNumberContact(Id Id){
        Contact c = [SELECT Id,ExternalComarchContactId__c FROM Contact WHERE Id=:Id];

        if(c.ExternalComarchContactId__c ==''||c.ExternalComarchContactId__c == null){
            c.ExternalComarchContactId__c = getNumber('Contact');
            Database.DMLOptions dml = new Database.DMLOptions();
            dml.DuplicateRuleHeader.allowSave = true;
            Database.Update(c,dml);
        }
    }*/

    public static string getNumber(string objectType){

        string comarchNumber;
        String newNumber;
        Comarch_Number__c cNumberObj = [SELECT Id,Comarch_Number_Prefix__c,Comarch_Number__c FROM Comarch_Number__c WHERE Object__c =:objectType FOR UPDATE];
        if(cNumberObj.Comarch_Number_Prefix__c != null){
            comarchNumber = cNumberObj.Comarch_Number_Prefix__c+cNumberObj.Comarch_Number__c;
        }else{
            comarchNumber =cNumberObj.Comarch_Number__c;
        }
        
        Integer i = Integer.valueOf(cNumberObj.Comarch_Number__c);
        i++;
        newNumber = String.valueOf(i);
        while(newNumber.length()<8){
            newNumber = '0'+newNumber;
        }
        cNumberObj.Comarch_Number__c = newNumber;

        Update cNumberObj;
        return comarchNumber;    



    }

}