force-app/main/default/objects/Account/fields/ComarchAccountNumber__c.field-meta.xml
<CustomField>
    <fullName>ComarchAccountNumber__c</fullName>
    <externalId>true</externalId>
    <label>Comarch Account Number</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Account.recordType-meta.xml
<RecordType>
    <fullName>Account</fullName>
    <active>true</active>
    <label>Account</label>
</RecordType>

force-app/main/default/objects/AccountBuildingProjectRelation__c/AccountBuildingProjectRelation__c.object-meta.xml
<CustomObject>
    <label>Account Building Project Relation</label>
    <nameField>
        <displayFormat>ABP-{00}</displayFormat>
        <label>Account Building Project Relation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Building Project Relations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/AccountBuildingProjectRelation__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.Blocked__c</field>
            <operation>notEqual</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Building Projects</relationshipLabel>
    <relationshipName>AccountBuildingProject</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/AccountBuildingProjectRelation__c/fields/BuildingProject__c.field-meta.xml
<CustomField>
    <fullName>BuildingProject__c</fullName>
    <label>Building Project</label>
    <referenceTo>BuildingProject__c</referenceTo>
    <relationshipLabel>Project Participants</relationshipLabel>
    <relationshipName>AccountBuildingProject</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/AccountBuildingProjectRelation__c/fields/Role__c.field-meta.xml
<CustomField>
    <fullName>Role__c</fullName>
    <label>Role</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Architect</fullName>
            </value>
            <value>
                <fullName>General Constructor</fullName>
            </value>
            <value>
                <fullName>Planner of cladding</fullName>
            </value>
            <value>
                <fullName>Building Authority</fullName>
            </value>
            <value>
                <fullName>Builder/ Awarding Office</fullName>
            </value>
            <value>
                <fullName>Investor</fullName>
            </value>
            <value>
                <fullName>Datenpflege ausstehend</fullName>
            </value>
            <value>
                <fullName>Project Manager</fullName>
            </value>
            <value>
                <fullName>Projektsteuerer</fullName>
                <isActive>false</isActive>
                <label>Projektsteuerer</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Bidder__c/Bidder__c.object-meta.xml
<CustomObject>
    <label>Bieter</label>
    <nameField>
        <label>Bidder Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Bieter</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Bidder__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Suggested For Bidder List</relationshipLabel>
    <relationshipName>Bidders</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Bidder__c/fields/Building_Project__c.field-meta.xml
<CustomField>
    <fullName>Building_Project__c</fullName>
    <label>Building Project</label>
    <referenceTo>BuildingProject__c</referenceTo>
    <relationshipName>Bidders</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Bidder__c/fields/ContactPerson__c.field-meta.xml
<CustomField>
    <fullName>ContactPerson__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact Person</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.AccountId</field>
            <operation>equals</operation>
            <valueField>$Source.Account__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Bidders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/BuildingProject__c/BuildingProject__c.object-meta.xml
<CustomObject>
    <label>Bauvorhaben</label>
    <nameField>
        <label>Building Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Bauvorhaben</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/BuildingProject__c/fields/ComarchBuildingProjectNumber__c.field-meta.xml
<CustomField>
    <fullName>ComarchBuildingProjectNumber__c</fullName>
    <externalId>true</externalId>
    <label>Comarch Building Project Number</label>
    <length>40</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/BuildingProject__c/fields/Stage__c.field-meta.xml
<CustomField>
    <fullName>Stage__c</fullName>
    <label>Stage</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Research</fullName>
                <default>true</default>
                <label>Research</label>
            </value>
            <value>
                <fullName>Consulting/ Planning</fullName>
            </value>
            <value>
                <fullName>Tender &amp; Quote</fullName>
            </value>
            <value>
                <fullName>Award Fabricator</fullName>
            </value>
            <value>
                <fullName>Award System house</fullName>
            </value>
            <value>
                <fullName>Execution</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
                <label>Completed</label>
            </value>
            <value>
                <fullName>Award</fullName>
                <isActive>false</isActive>
                <label>Award</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/ExternalComarchContactId__c.field-meta.xml
<CustomField>
    <fullName>ExternalComarchContactId__c</fullName>
    <externalId>true</externalId>
    <label>Comarch Contact Number</label>
    <length>20</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Systems__c/Systems__c.object-meta.xml
<CustomObject>
    <label>System</label>
    <nameField>
        <displayFormat>SYS-{0000000000}</displayFormat>
        <label>Systems Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Systems</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Systems__c/fields/BuildingProjectSystem__c.field-meta.xml
<CustomField>
    <fullName>BuildingProjectSystem__c</fullName>
    <label>Building Project</label>
    <referenceTo>BuildingProject__c</referenceTo>
    <relationshipLabel>Systems</relationshipLabel>
    <relationshipName>Systems</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Systems__c/fields/SystemSize__c.field-meta.xml
<CustomField>
    <fullName>SystemSize__c</fullName>
    <label>System Size</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Systems__c/fields/SystemType__c.field-meta.xml
<CustomField>
    <fullName>SystemType__c</fullName>
    <label>System Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Aluminiumfassade</fullName>
                <label>Aluminum facade</label>
            </value>
            <value>
                <fullName>Holzfassade</fullName>
                <label>Wooden facade</label>
            </value>
            <value>
                <fullName>Stahlfassade</fullName>
                <label>Steel facade</label>
            </value>
            <value>
                <fullName>Aluminiumdach</fullName>
                <label>Aluminum roof</label>
            </value>
            <value>
                <fullName>Holzdach</fullName>
                <label>Wooden roof</label>
            </value>
            <value>
                <fullName>Stahldach</fullName>
                <label>Steel roof</label>
            </value>
            <value>
                <fullName>Aluminium Lochfenster/-Fensterbänder</fullName>
                <label>Aluminum punched window / window frames</label>
            </value>
            <value>
                <fullName>Einsatzfenster</fullName>
                <label>Operational window</label>
            </value>
            <value>
                <fullName>elementierte Lösung THERM+</fullName>
                <label>Modular Solution THERM+</label>
            </value>
            <value>
                <fullName>elementierte Lösung FRAME+</fullName>
                <label>Modular Solution FRAME+</label>
            </value>
            <value>
                <fullName>Hebe Schiebe Türe</fullName>
                <label>Lift-and-slide door</label>
            </value>
            <value>
                <fullName>Holz-Aluminium Fenster</fullName>
                <label>Wood-Aluminum Windows</label>
            </value>
            <value>
                <fullName>Aluminiumtüre</fullName>
                <label>Aluminum door</label>
            </value>
            <value>
                <fullName>Brandschutztüre</fullName>
                <label>Fire protection door</label>
            </value>
            <value>
                <fullName>Dachfenster</fullName>
                <label>Roof window</label>
            </value>
            <value>
                <fullName>Aluminium-Dach</fullName>
                <isActive>false</isActive>
                <label>Aluminium-Dach</label>
            </value>
            <value>
                <fullName>Aluminium-Fassade</fullName>
                <isActive>false</isActive>
                <label>Aluminium-Fassade</label>
            </value>
            <value>
                <fullName>Aluminium-Fenster</fullName>
                <isActive>false</isActive>
                <label>Aluminium-Fenster</label>
            </value>
            <value>
                <fullName>Holz-Dach</fullName>
                <isActive>false</isActive>
                <label>Holz-Dach</label>
            </value>
            <value>
                <fullName>Holz-Fassade</fullName>
                <isActive>false</isActive>
                <label>Holz-Fassade</label>
            </value>
            <value>
                <fullName>Stahl-Dach</fullName>
                <isActive>false</isActive>
                <label>Stahl-Dach</label>
            </value>
            <value>
                <fullName>Stahl-Fassade</fullName>
                <isActive>false</isActive>
                <label>Stahl-Fassade</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Systems__c/fields/SystemUnit__c.field-meta.xml
<CustomField>
    <fullName>SystemUnit__c</fullName>
    <label>System Unit</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>sqm</fullName>
                <default>true</default>
                <label>m²</label>
            </value>
            <value>
                <fullName>quantity</fullName>
            </value>
            <value>
                <fullName>linear meters</fullName>
            </value>
            <value>
                <fullName>kg</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/V11_TestBuildingProjectController.cls
@istest
public class V11_TestBuildingProjectController {
    
    @TestSetup
    static void setupData()
    {
        Account a = new Account();
        a.Name = 'test';
        a.Type = 'Architect';
        a.ComarchAccountNumber__c = 'test';
        a.BillingStreet = 'Test Street 1';
        a.BillingCity = 'Testtown';
        a.BillingPostalCode = '12345';
        a.BillingCountryCode = 'DE';
        insert a;
        
        Contact c = new Contact();
        c.LastName = 'test';
        c.Email = 'test@test.de';
        c.AccountId = a.id;
        c.MobilePhone = '+491234';
        c.Phone = '+491234';
        c.Email = 'test@test.com';
        c.ExternalComarchContactId__c = '123';
        insert c;
        
        BuildingProject__c bp = new BuildingProject__c();
        bp.Name = 'test';
        bp.Amount__c = 123;
        bp.Stage__c = 'Research';
        bp.ComarchBuildingProjectNumber__c='Test';
        bp.ProjectAddress__Street__s='Pettenkoferstraße 13';
        bp.ProjectAddress__City__s='Berlin';
        bp.ProjectAddress__PostalCode__s='10247';
        bp.ProjectAddress__CountryCode__s='DE';
        insert bp;
        
        Bidder__c bidder = new Bidder__c();
        bidder.ContactPerson__c = c.Id;
        bidder.Building_Project__c = bp.Id;
        bidder.Account__c = a.Id;
        insert bidder;

        AccountBuildingProjectRelation__c ar = new AccountBuildingProjectRelation__c();
        ar.Account__c = a.Id;
        ar.BuildingProject__c = bp.Id;
        ar.Role__c = 'Architect';
        insert ar;
        
        AccountBuildingProjectRelation__c gc = new AccountBuildingProjectRelation__c();
        gc.Account__c = a.Id;
        gc.BuildingProject__c = bp.Id;
        gc.Role__c = 'General Constructor';
        insert gc;
        
        AccountBuildingProjectRelation__c p = new AccountBuildingProjectRelation__c();
        p.Account__c = a.Id;
        p.BuildingProject__c = bp.Id;
        p.Role__c = 'Planner of cladding';
        insert p;
        
        AccountBuildingProjectRelation__c ba = new AccountBuildingProjectRelation__c();
        ba.Account__c = a.Id;
        ba.BuildingProject__c = bp.Id;
        ba.Role__c = 'Building Authority';
        insert ba;
        
        Systems__c sy = new Systems__c();
        sy.BuildingProjectSystem__c = bp.Id;
        sy.SystemType__c = 'Holzdach';
        sy.SystemUnit__c = 'sqm';
        sy.SystemSize__c = 30.0;
        insert sy;
    }
    
    static testmethod void buildingProjectControllerTest()
    {        
        List<BuildingProject__c> bps = [select id, ComarchBuildingProjectNumber__c, Name from BuildingProject__c];        
        ApexPages.StandardController sc = new ApexPages.StandardController(bps.get(0));
        
        Test.startTest();
        V11_BuildingProjectControllerExtension v11Controller = new V11_BuildingProjectControllerExtension(sc);
        v11Controller.getBidders();  
        v11Controller.getArchs();      
        v11Controller.getSystems();
        v11Controller.getProjectSalesRep();
        v11Controller.getBAuth();
        v11Controller.getPlanner();
        v11Controller.getGC();

        Test.stopTest();
        
    }

}