force-app/main/default/objects/AccountContactRelation/fields/InitialContactRelation__c.field-meta.xml
<CustomField>
    <fullName>InitialContactRelation__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Initial Contact Relation</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/AccountContactRelation/fields/Synced__c.field-meta.xml
<CustomField>
    <fullName>Synced__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Synced</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact__c/Contact__c.object-meta.xml
<CustomObject>
    <description>Messebesucher</description>
    <label>Trade Fair Contact</label>
    <nameField>
        <displayFormat>TFC-{00000}</displayFormat>
        <label>Trade Fair Contact</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Trade Fair Contacts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Contact__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Trade Fair Contacts</relationshipLabel>
    <relationshipName>Trade_Fair_Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/obcAccountContactRelation__c/obcAccountContactRelation__c.object-meta.xml
<CustomObject>
    <label>Outbound Account Contact Relation</label>
    <nameField>
        <label>Outbound Account Contact Relation</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Outbound Account Contact Relations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/obcAccountContactRelation__c/fields/InitialContactRelation__c.field-meta.xml
<CustomField>
    <fullName>InitialContactRelation__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Initial Contact Relation</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/obcAccountContactRelation__c/fields/Outbound_Call__c.field-meta.xml
<CustomField>
    <fullName>Outbound_Call__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Outbound Call</label>
    <referenceTo>OutboundCall__c</referenceTo>
    <relationshipLabel>Outbound Account Contact Relations</relationshipLabel>
    <relationshipName>Outbound_Account_Contact_Relations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OutboundCall__c/OutboundCall__c.object-meta.xml
<CustomObject>
    <label>Outbound Call</label>
    <nameField>
        <displayFormat>OC-{0000000000}</displayFormat>
        <label>Outbound Call Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Outbound Calls</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/OutboundCall__c/fields/Data__c.field-meta.xml
<CustomField>
    <fullName>Data__c</fullName>
    <label>Data</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/V11_sendRelationsToComarch.cls
public class V11_sendRelationsToComarch implements Queueable,Database.AllowsCallouts {

    String obcId;
    String operation;

    public V11_sendRelationsToComarch(String obcId, String operation) {
        this.obcId = obcId;
        this.operation = operation;

    }
    public void execute(QueueableContext context){

        
        obcAccountContactRelation__c obcACR = [SELECT Id,Account__c,Contact__c,Id__c,InitialContactRelation__c FROM obcAccountContactRelation__c WHERE Outbound_Call__c=:obcID];

        String envHeader='<?xml version="1.0"?><soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:par="http://webservices.semiramis.com/2006-01/Import/extended/PARTNERSALESFORCE" xmlns:data="http://webservices.semiramis.com/2006-01/Import/extended/PARTNERSALESFORCE/data" xmlns:com="http://webservices.semiramis.com/2006-01/common"><soapenv:Header/>'+
        '<soapenv:Body><par:process><par:in0><par:warningsMode>CONFIRM_ALL</par:warningsMode><par:correctionMode>NONE</par:correctionMode><par:processLogLevel>ENABLED</par:processLogLevel><par:importData>';
        String envFooter = '</par:importData></par:in0></par:process></soapenv:Body></soapenv:Envelope>';
        String body = '';

        if(obcACR.InitialContactRelation__c){

            body = '<data:Partner mode="update">'+
            '<data:number>'+obcACR.Contact__c+'</data:number>'+
            '<data:Employee mode="create">'+ 
            '<data:PartnerRelations mode="create">'+
            '<data:Target>'+
            '<data:number>'+obcACR.Account__c+'</data:number>'+
            '</data:Target><data:Type><data:name>Employee</data:name></data:Type>'+
            '</data:PartnerRelations>'+       
            '</data:Employee></data:Partner>';

        }else{

            if(operation == 'delete'){

                body = '<data:Partner mode="update">'+
                '<data:number>'+obcACR.Contact__c+'</data:number>'+
                '<data:Employee mode="update">'+ 
                '<data:PartnerRelations mode="delete">'+
                '<data:Target>'+
                '<data:number>'+obcACR.Account__c+'</data:number>'+
                '</data:Target><data:Type><data:name>Employee</data:name></data:Type>'+
                '</data:PartnerRelations>'+       
                '</data:Employee></data:Partner>';
    
            }else if(operation == 'create'){
    
                body = '<data:Partner mode="update">'+
                '<data:number>'+obcACR.Contact__c+'</data:number>'+
                '<data:Employee mode="update">'+ 
                '<data:PartnerRelations mode="create">'+
                '<data:Target>'+
                '<data:number>'+obcACR.Account__c+'</data:number>'+
                '</data:Target><data:Type><data:name>Employee</data:name></data:Type>'+
                '</data:PartnerRelations>'+       
                '</data:Employee></data:Partner>';
    
            }

        }


        String requestString = envHeader + body + envFooter;
        HttpRequest req = new HttpRequest();
        String userAuth = V11_helperClass.getPassword('Comarch');
        req.setHeader('Authorization','Basic '+userAuth);
        req.setEndpoint(V11_helperClass.getEndpoint('RelationsImport'));
        req.setMethod('POST');
        req.setBody(requestString);
        req.setHeader('Content-Type', 'text/xml');
        req.setHeader('SOAPAction', '""');
        Http http = new Http();
        HTTPResponse res;
        res = http.send(req);


        
        OutboundCall__c obcUpdate = [SELECT Id FROM OutboundCall__c WHERE Id =:obcId];
        Database.DMLOptions dml = new Database.DMLOptions();
        dml.DuplicateRuleHeader.allowSave = true;
        dml.DuplicateRuleHeader.runAsCurrentUser = true;
        obcUpdate.Data__c = requestString;
        obcUpdate.Data__c = requestString;
        obcUpdate.ErrorMessage__c = res.getBody();
        XmlStreamReader reader = res.getXmlStreamReader();
        Boolean hasError = false;
        while(reader.hasNext()){
            if(reader.getLocalName()=='hasErrorFile'){
                reader.next();
                if(reader.hasText()){
                    hasError = Boolean.valueOf(reader.getText());
                    break;
                }
            }
            reader.next();
        }
        
        
        
        if(!hasError && res.getStatusCode() == 200){
            if(operation != 'delete'){
                AccountContactRelation acrUpdate = [SELECT Id FROM AccountContactRelation WHERE Id =:obcACR.Id__c];
                acrUpdate.Synced__c = true;
                acrUpdate.InitialContactRelation__c = false;
                Database.update(acrUpdate, dml);
            }
            obcUpdate.Status__c = 'Success';

            Database.update(obcUpdate, dml);
        }else{

            obcUpdate.Status__c = 'Error';          
            Database.update(obcUpdate, dml);
        }  

    }
}