force-app/main/default/objects/AccountContactRelation/fields/InitialContactRelation__c.field-meta.xml
<CustomField>
    <fullName>InitialContactRelation__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Initial Contact Relation</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/AccountContactRelation/fields/Synced__c.field-meta.xml
<CustomField>
    <fullName>Synced__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Synced</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/ComarchSyncStatusContact__c.field-meta.xml
<CustomField>
    <fullName>ComarchSyncStatusContact__c</fullName>
    <defaultValue>&quot;-&quot;</defaultValue>
    <label>Comarch Sync Status</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Language__c.field-meta.xml
<CustomField>
    <fullName>Language__c</fullName>
    <label>Language</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>de</fullName>
                <default>true</default>
                <label>de</label>
            </value>
            <value>
                <fullName>en</fullName>
            </value>
            <value>
                <fullName>es</fullName>
            </value>
            <value>
                <fullName>fr</fullName>
            </value>
            <value>
                <fullName>it</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Synced__c.field-meta.xml
<CustomField>
    <fullName>Synced__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Synced</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Title__c.field-meta.xml
<CustomField>
    <fullName>Title__c</fullName>
    <label>Title</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>ArchitektIn</fullName>
            </value>
            <value>
                <fullName>BSc.</fullName>
            </value>
            <value>
                <fullName>DI Mag.</fullName>
            </value>
            <value>
                <fullName>Dipl.Ing.</fullName>
                <label>Dipl. Ing.</label>
            </value>
            <value>
                <fullName>Dipl. Ing. (FH)</fullName>
            </value>
            <value>
                <fullName>Dipl.-Ing. Arch (FH)</fullName>
            </value>
            <value>
                <fullName>Dipl.-Ing. ArchitektIn</fullName>
            </value>
            <value>
                <fullName>Dipl. Wirt.-Ing (FH)</fullName>
            </value>
            <value>
                <fullName>Dr.</fullName>
            </value>
            <value>
                <fullName>Dr. Dipl. Ing.</fullName>
            </value>
            <value>
                <fullName>Dr. Ing.</fullName>
            </value>
            <value>
                <fullName>Ing.</fullName>
            </value>
            <value>
                <fullName>Ing. Mag.</fullName>
            </value>
            <value>
                <fullName>M.A. Architektin</fullName>
            </value>
            <value>
                <fullName>M. Arch.</fullName>
            </value>
            <value>
                <fullName>Mag.</fullName>
            </value>
            <value>
                <fullName>Mag. Arch.</fullName>
            </value>
            <value>
                <fullName>Mag. MBA</fullName>
            </value>
            <value>
                <fullName>MBA</fullName>
            </value>
            <value>
                <fullName>Prof.</fullName>
            </value>
            <value>
                <fullName>Prof. Dipl. Ing.</fullName>
            </value>
            <value>
                <fullName>Prof. Dr.</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/obcContact__c/obcContact__c.object-meta.xml
<CustomObject>
    <label>Outbound Contact</label>
    <nameField>
        <displayFormat>OBCC-{00000000}</displayFormat>
        <label>Outbound Contact</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Outbound Contacts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/obcContact__c/fields/Account_ID_comarch__c.field-meta.xml
<CustomField>
    <fullName>Account_ID_comarch__c</fullName>
    <label>Account ID comarch</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/obcContact__c/fields/Old_Mobile__c.field-meta.xml
<CustomField>
    <fullName>Old_Mobile__c</fullName>
    <label>Old Mobile</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/obcContact__c/fields/Old_Phone__c.field-meta.xml
<CustomField>
    <fullName>Old_Phone__c</fullName>
    <label>Old Phone</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/obcContact__c/fields/Outbound_Call__c.field-meta.xml
<CustomField>
    <fullName>Outbound_Call__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Outbound Call</label>
    <referenceTo>OutboundCall__c</referenceTo>
    <relationshipLabel>Outbound Contacts</relationshipLabel>
    <relationshipName>Outbound_Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OutboundCall__c/OutboundCall__c.object-meta.xml
<CustomObject>
    <label>Outbound Call</label>
    <nameField>
        <displayFormat>OC-{0000000000}</displayFormat>
        <label>Outbound Call Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Outbound Calls</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/OutboundCall__c/fields/Data__c.field-meta.xml
<CustomField>
    <fullName>Data__c</fullName>
    <label>Data</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/V11_sendContactToComarch.cls
public class V11_sendContactToComarch implements Queueable,Database.AllowsCallouts {
    
    String obcId;
    String operation;

    public V11_sendContactToComarch(String obcId, String operation) {

        this.obcId = obcId;
        this.operation = operation;

    }

    public void execute(QueueableContext context){
        String envHeader='<?xml version="1.0"?><soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:par="http://webservices.semiramis.com/2006-01/Import/extended/PARTNERSALESFORCE" xmlns:data="http://webservices.semiramis.com/2006-01/Import/extended/PARTNERSALESFORCE/data" xmlns:com="http://webservices.semiramis.com/2006-01/common"><soapenv:Header/>'+
        '<soapenv:Body><par:process><par:in0><par:warningsMode>CONFIRM_ALL</par:warningsMode><par:correctionMode>NONE</par:correctionMode><par:processLogLevel>ENABLED</par:processLogLevel><par:importData>';
        String envFooter = '</par:importData></par:in0></par:process></soapenv:Body></soapenv:Envelope>';
        String body='';

        obcContact__c contact = [SELECT Id,Comarch_ID__c,First_Name__c,Middle_Name__c,Name__c,Salutation__c,Title__c,Account_ID_comarch__c,Language__c,Email__c,Mobile__c,Phone__c,Old_Email__c,Old_Mobile__c,Old_Phone__c,Id__c FROM obcContact__c WHERE Outbound_Call__c =: obcId];

      
            //TODO
            body = body +'<data:Partner mode="'+operation+'">'+
            '<data:number>'+V11_helperClass.getStringValue(contact.Comarch_ID__c)+'</data:number>'+
            '<data:type>EXTERNAL</data:type>'+
            '<data:person>'+
            '<data:givenName>'+V11_helperClass.getStringValue(contact.First_Name__c)+'</data:givenName><data:middleNames>'+V11_helperClass.getStringValue(contact.Middle_Name__c)+'</data:middleNames><data:surname>'+V11_helperClass.getStringValue(contact.Name__c)+'</data:surname>'+
            '<data:gender>MALE</data:gender>'+
            '<data:Salutation><data:name>'+V11_helperClass.getStringValue(contact.Salutation__c)+'</data:name></data:Salutation>'+
            '<data:Title><data:name>'+V11_helperClass.getStringValue(contact.Title__c)+'</data:name></data:Title>'+
            '</data:person>'+
            '<data:EntityExtension mode="create">'+
            '<data:SALESFORCEID mode="create"> <data:value>'+V11_helperClass.getStringValue(contact.Id__c)+'</data:value> </data:SALESFORCEID>'+ 
            '</data:EntityExtension>'+
            '<data:human>true</data:human>'+
            '<data:Language><data:isoCode>'+V11_helperClass.getStringValue(contact.Language__c)+'</data:isoCode></data:Language>'+
            '<data:MaintainingOrganization><data:number>910000</data:number></data:MaintainingOrganization>';
            if(operation == 'create'){
                body = body + '<data:CommunicationData><data:commData>'+V11_helperClass.getStringValue(contact.Email__c)+'</data:commData><data:preferred>false</data:preferred><data:Method><data:name>300</data:name></data:Method></data:CommunicationData>'+
                '<data:CommunicationData><data:commData>'+V11_helperClass.getStringValue(contact.Mobile__c)+'</data:commData><data:preferred>false</data:preferred><data:Method><data:name>120</data:name></data:Method></data:CommunicationData>'+
                '<data:CommunicationData><data:commData>'+V11_helperClass.getStringValue(contact.Phone__c)+'</data:commData><data:preferred>true</data:preferred><data:Method><data:name>100</data:name></data:Method></data:CommunicationData>';
            }else{
                if(contact.Email__c != contact.Old_Email__c){
                    body = body + '<data:CommunicationData mode="create"><data:commData>'+V11_helperClass.getStringValue(contact.Email__c)+'</data:commData><data:preferred>false</data:preferred><data:Method><data:name>300</data:name></data:Method></data:CommunicationData>';
                    if(contact.Old_Email__c != null){
                        body = body +'<data:CommunicationData mode="delete"><data:commData>'+V11_helperClass.getStringValue(contact.Old_Email__c)+'</data:commData><data:preferred>false</data:preferred><data:Method><data:name>300</data:name></data:Method></data:CommunicationData>';
                    }

                }if(contact.Mobile__c != contact.Old_Mobile__c){
                    body = body + '<data:CommunicationData mode="create"><data:commData>'+V11_helperClass.getStringValue(contact.Mobile__c)+'</data:commData><data:preferred>false</data:preferred><data:Method><data:name>120</data:name></data:Method></data:CommunicationData>';
                    if(contact.Old_Mobile__c != null){
                        body = body + '<data:CommunicationData mode="delete"><data:commData>'+V11_helperClass.getStringValue(contact.Old_Mobile__c)+'</data:commData><data:preferred>false</data:preferred><data:Method><data:name>120</data:name></data:Method></data:CommunicationData>';
                    }                    

                }if(contact.Phone__c != contact.Old_Phone__c){
                    body = body + '<data:CommunicationData mode="create"><data:commData>'+V11_helperClass.getStringValue(contact.Phone__c)+'</data:commData><data:preferred>false</data:preferred><data:Method><data:name>100</data:name></data:Method></data:CommunicationData>';
                    if(contact.Old_Phone__c != null){
                        body = body + '<data:CommunicationData mode="delete"><data:commData>'+V11_helperClass.getStringValue(contact.Old_Phone__c)+'</data:commData><data:preferred>false</data:preferred><data:Method><data:name>100</data:name></data:Method></data:CommunicationData>';
                    }                    
                }                
            }

            body = body +'</data:Partner>';
                


        String requestString = envHeader + body + envFooter;
        HttpRequest req = new HttpRequest();
        String userAuth = V11_helperClass.getPassword('Comarch');
        req.setHeader('Authorization','Basic '+userAuth);
        req.setEndpoint(V11_helperClass.getEndpoint('ContactImport'));
        req.setMethod('POST');
        req.setBody(requestString);
        req.setHeader('Content-Type', 'text/xml');
        req.setHeader('SOAPAction', '""');
        Http http = new Http();
        HTTPResponse res;      
        res = http.send(req);


        Contact cUpdate = [SELECT Id FROM Contact WHERE Id =:contact.Id__c];
        OutboundCall__c obcUpdate = [SELECT Id FROM OutboundCall__c WHERE Id =:obcId];
        Database.DMLOptions dml = new Database.DMLOptions();
        dml.DuplicateRuleHeader.allowSave = true;
        dml.DuplicateRuleHeader.runAsCurrentUser = true;
        obcUpdate.Data__c = requestString;
        obcUpdate.ErrorMessage__c = res.getBody();
        XmlStreamReader reader = res.getXmlStreamReader();
        Boolean hasError = false;
        while(reader.hasNext()){
            if(reader.getLocalName()=='hasErrorFile'){
                reader.next();
                if(reader.hasText()){
                    hasError = Boolean.valueOf(reader.getText());
                    break;
                }
            }
            reader.next();
        }
        
        
        if(!hasError && res.getStatusCode() == 200){

            obcUpdate.Status__c = 'Success';           
            cUpdate.ComarchSyncStatusContact__c = 'Success';
            cUpdate.Synced__c = true;
            Database.update(cUpdate, dml);
            Database.update(obcUpdate, dml);
            
            if(operation == 'create'){
                List<AccountContactRelation> acrList = [SELECT Id FROM AccountContactRelation WHERE ContactId =:cUpdate.Id ];
                for(AccountContactRelation acr: acrList){
                    acr.InitialContactRelation__c = true;
                }
                Database.update(acrList, dml);    
            }                              


        }else{

            cUpdate.ComarchSyncStatusContact__c = 'Error';
            obcUpdate.Status__c = 'Error';          
            Database.update(cUpdate, dml);
            Database.update(obcUpdate, dml);
        }     
            


    }
}